/**
 * Peaks tab — browse every peak in the region and tag it dream / planned /
 * attempted / done.
 *
 * Peaks come from data/peaks.geojson, a snapshot of OpenStreetMap generated by
 * scripts/fetch-peaks.mjs. Statuses come from PeakStore (store.js), which hides
 * whether they live in this browser or in a database behind one interface.
 */

const PEAKS_URL = 'data/peaks.geojson';

const PEAK_STYLE = `https://api.maptiler.com/maps/01977a3c-1420-7d86-8992-edcec1cbca8d/style.json?key=${CONFIG?.MAPTILER_API_KEY}`;

/** Order matters — it drives the legend, the filter list and the picker. */
const STATUSES = {
  done:      { label: 'Done',      color: '#2f7d32', hint: 'Summited' },
  planned:   { label: 'Planned',   color: '#f0a500', hint: 'Actually going' },
  dream:     { label: 'Dream',     color: '#7b5ea7', hint: 'Someday' },
  attempted: { label: 'Attempted', color: '#d1495b', hint: 'Tried, turned back' },
  none:      { label: 'Untagged',  color: '#8d9296', hint: 'Not on the list' }
};
const TAGGED = Object.keys(STATUSES).filter(s => s !== 'none');

/**
 * Country names for any code, now that a peak can come from anywhere. The
 * browser already knows them in every language it speaks, which beats a list
 * that stops at the seven countries the Alps snapshot happens to cover.
 */
const REGION_NAMES = (() => {
  try {
    return new Intl.DisplayNames(['en'], { type: 'region' });
  } catch {
    return null;
  }
})();

const COUNTRY_NAMES = new Proxy({}, {
  get: (_, code) => {
    if (typeof code !== 'string' || code === '??') return undefined;
    try {
      return REGION_NAMES?.of(code) ?? undefined;
    } catch {
      return undefined;   // not a region code, e.g. a name we were handed
    }
  },
  has: () => true
});

/**
 * The country a peak stands in, asked of MapTiler's geocoder — one request,
 * only when tagging something that has no country of its own, which is every
 * peak taken from the basemap's tiles. It answered Everest as Nepal where a
 * boundary file said China, so it is worth the round trip.
 */
async function resolveCountry(lon, lat) {
  const key = typeof CONFIG !== 'undefined' ? CONFIG.MAPTILER_API_KEY : null;
  if (!key) return null;
  try {
    const url = `https://api.maptiler.com/geocoding/${lon},${lat}.json?key=${key}&types=country&limit=1`;
    const response = await fetch(url);
    if (!response.ok) return null;
    const feature = (await response.json()).features?.[0];
    const code = feature?.properties?.country_code ?? feature?.properties?.['ISO3166-1'];
    return code ? code.toUpperCase() : null;
  } catch (err) {
    console.warn('[peaks] could not resolve the country:', err);
    return null;
  }
}

const state = {
  features: [],              // GeoJSON features, properties.status kept current
  byId: new Map(),           // peak id (string) → feature, to avoid rescanning
  statuses: new Map(),       // peak id (string) → { status, date, note, … }, owned by PeakStore
  map: null,
  popup: null,
  hoverPopup: null,
  // route id → the track drawn on the map. Tracks stay until cleared, so a
  // planned line can be held against one already walked.
  drawn: new Map(),
  filters: {
    minEle: 1000,
    maxEle: 3000,
    statuses: new Set([...TAGGED, 'none']),
    countries: new Set(),    // empty = all
    search: '',
    // Shifts the whole zoom ladder: negative shows more, positive shows less.
    detail: 0
  }
};

/**
 * An untagged peak is drawn once the map reaches the zoom its isolation earned
 * it, so a secondary summit like Kleinglockner (70 m from Großglockner) stays
 * hidden until you are close enough for it to mean something.
 *
 * Tagged peaks have no zoom tier. They are drawn at every zoom and compete for
 * space instead: where two would overlap, the one earlier in this list keeps
 * its place, so a done peak is never pushed out by a planned one. Lower
 * statuses fill whatever room is left, and filtering a status out frees its
 * room for the rest.
 */
const STATUS_PRIORITY = ['done', 'planned', 'dream', 'attempted'];

/**
 * The peak's own zoom tier, defaulting to "always visible" when the property is
 * absent — an older snapshot should degrade to showing everything, never to a
 * blank map.
 */
const PEAK_MIN_ZOOM = ['coalesce', ['get', 'minZoom'], 0];

/**
 * The basemap's own peaks, kept behind a switch.
 *
 * MapTiler's tiles carry a `mountain_peak` layer worldwide from zoom 7 — name,
 * elevation and a rank of 1 (most prominent) to 5 — and they are already
 * downloaded to draw the map, so this costs no request and no quota. It is
 * what puts Aconcagua on the map without shipping a snapshot of the Andes.
 *
 * What it does not carry is a country or an OSM id, which is why it is an
 * addition rather than a replacement: the country filter only knows about
 * peaks from the snapshot and from your own list.
 */
const TILE_PEAKS = { source: 'maptiler_planet', sourceLayer: 'mountain_peak', key: 'mmj.tile-peaks' };

/**
 * An id for a peak that has none of its own.
 *
 * Tiles give no OSM node id, so identity comes from position, rounded to five
 * decimals — about a metre, far finer than two summits are ever apart. The
 * 1e15 offset puts these above every real OSM node id (~1.3e10 today), so the
 * two id spaces can never meet.
 */
function idFromPosition(lon, lat) {
  const latPart = Math.round((lat + 90) * 1e5);
  const lonPart = Math.round((lon + 180) * 1e5);
  return 1e15 + latPart * 36000001 + lonPart;
}

// ─── Load ─────────────────────────────────────────────────────────────────────

async function initPeaks() {
  const root = document.getElementById('tab-peaks');

  let peaks;
  try {
    peaks = await fetch(PEAKS_URL).then(r => {
      if (!r.ok) throw new Error(`${PEAKS_URL} → HTTP ${r.status}`);
      return r.json();
    });
  } catch (err) {
    console.error('[peaks]', err);
    root.querySelector('#peaks-map').innerHTML =
      `<p class="peaks-error">Could not load ${PEAKS_URL}. Run <code>node scripts/fetch-peaks.mjs</code> to generate it.</p>`;
    return;
  }

  state.statuses = await PeakStore.open();
  await RouteStore.open();

  state.features = peaks.features.map(f => ({
    ...f,
    properties: {
      ...f.properties,
      country: f.properties.country ?? '??',
      status: state.statuses.get(String(f.properties.id))?.status ?? 'none'
    }
  }));

  state.byId = new Map(state.features.map(f => [String(f.properties.id), f]));
  mergeAccountPeaks();

  const elevations = state.features.map(f => f.properties.ele);
  // The sliders run over what the snapshot holds, but the map now shows peaks
  // from beyond it. A slider at its top therefore means "no limit" rather than
  // 4900 m, or the Alps would quietly hide Aconcagua.
  state.eleRange = {
    min: Math.floor(Math.min(...elevations) / 100) * 100,
    max: Math.ceil(Math.max(...elevations) / 100) * 100
  };
  state.filters.minEle = state.eleRange.min;
  state.filters.maxEle = state.eleRange.max;

  console.log(`[peaks] ${state.features.length} peaks, ${state.statuses.size} tagged`);

  buildPanel(peaks);
  buildMap();

  // Signing in or out swaps the whole list for the other backend's.
  PeakStore.onChange(async statuses => {
    state.statuses = statuses;
    for (const feature of state.features) {
      feature.properties.status = statuses.get(String(feature.properties.id))?.status ?? 'none';
    }
    // Routes live only in an account, so signing out empties them.
    clearTracks();
    await RouteStore.open();
    refreshSource();
    applyFilters();
    renderTaggedList();
    renderAccount();
  });
}

/**
 * Peaks your list holds that the snapshot does not — tagged from the basemap's
 * tiles, or from a snapshot that has since been regenerated without them.
 * They carry their own position, so they draw like any other peak and appear
 * at every zoom: a dream is worth seeing from across the continent.
 */
function mergeAccountPeaks() {
  let added = 0;
  for (const [id, entry] of state.statuses) {
    if (state.byId.has(id) || entry.lat == null || entry.lon == null) continue;
    const feature = {
      type: 'Feature',
      id: Number(id),
      geometry: { type: 'Point', coordinates: [entry.lon, entry.lat] },
      properties: {
        id: Number(id),
        name: entry.name ?? 'Unnamed peak',
        ele: entry.ele ?? 0,
        country: entry.country ?? '??',
        source: entry.source ?? 'account',
        minZoom: 0,
        status: entry.status
      }
    };
    state.features.push(feature);
    state.byId.set(id, feature);
    added++;
  }
  if (added) console.log(`[peaks] ${added} peaks from your list that the snapshot does not have`);
}

// ─── Map ──────────────────────────────────────────────────────────────────────

const collection = () => ({ type: 'FeatureCollection', features: state.features });

function buildMap() {
  const map = new maplibregl.Map({
    container: 'peaks-map',
    style: PEAK_STYLE,
    center: [11.6, 47.55],
    zoom: 9,
    // v3 only takes a boolean here, so the credit goes on the control itself.
    attributionControl: false
  });
  state.map = map;

  map.addControl(new maplibregl.AttributionControl({
    compact: true,
    customAttribution: 'Peak data © OpenStreetMap contributors (ODbL)'
  }), 'bottom-right');
  map.addControl(new maplibregl.NavigationControl(), 'top-right');
  // Bottom-left belongs to the floating panel now.
  map.addControl(new maplibregl.ScaleControl({ maxWidth: 120 }), 'bottom-right');

  map.on('error', e => console.error('[peaks] map error:', e?.error?.message ?? e));

  map.on('load', () => {
    // The basemap labels its own peaks; ours carry the status, so drop theirs
    // rather than stacking two labels on one summit.
    for (const id of ['Peak labels', 'Peak labels (US)']) {
      if (map.getLayer(id)) map.setLayoutProperty(id, 'visibility', 'none');
    }

    map.addSource('peaks', { type: 'geojson', data: collection(), promoteId: 'id' });

    addStatusIcons(map);

    // Tracks go on first, so every peak draws over them.
    map.addSource('tracks', { type: 'geojson', data: trackCollection() });
    map.addLayer({
      id: 'tracks-casing',
      type: 'line',
      source: 'tracks',
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': '#ffffff',
        'line-width': ['interpolate', ['linear'], ['zoom'], 8, 3.5, 14, 8],
        'line-opacity': 0.75
      }
    });
    map.addLayer({
      id: 'tracks-line',
      type: 'line',
      source: 'tracks',
      layout: { 'line-join': 'round', 'line-cap': 'round' },
      paint: {
        'line-color': ['match', ['get', 'kind'],
          'done', STATUSES.done.color,
          'planned', STATUSES.planned.color,
          '#555'
        ],
        'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 14, 4]
      }
    });

    addTilePeakLayers(map);
    RouteDraw.addLayers(map);

    // A peak that dominates its surroundings should look like it. `rank` runs
    // from 0 for a minor secondary summit to 1 for something like Großglockner.
    const rank = ['interpolate', ['linear'], PEAK_MIN_ZOOM,
      6, 1,
      10, 0.55,
      14, 0
    ];

    // Untagged peaks: plain dots, which never collide, gated by zoom tier.
    map.addLayer({
      id: 'peaks-dots',
      type: 'circle',
      source: 'peaks',
      paint: {
        'circle-color': STATUSES.none.color,
        'circle-radius': ['interpolate', ['linear'], ['zoom'],
          7,  ['+', 1.5, ['*', rank, 3.5]],
          10, ['+', 2.5, ['*', rank, 4.5]],
          14, ['+', 4.5, ['*', rank, 6]]
        ],
        'circle-stroke-color': '#ffffff',
        'circle-stroke-width': 1,
        'circle-opacity': 0.85
      }
    });

    map.addLayer({
      id: 'peaks-labels',
      type: 'symbol',
      source: 'peaks',
      layout: {
        ...labelLayout(rank),
        // When two labels collide the more dominant peak keeps its name.
        'symbol-sort-key': PEAK_MIN_ZOOM
      },
      paint: LABEL_PAINT
    });

    // Tagged peaks: icons rather than circles, because only symbols take part
    // in collision. Added last, so they are placed before every other label
    // on the map and nothing untagged can crowd them out.
    const statusRank = ['match', ['get', 'status'],
      ...STATUS_PRIORITY.flatMap((key, i) => [key, i]),
      STATUS_PRIORITY.length
    ];
    map.addLayer({
      id: 'peaks-tagged',
      type: 'symbol',
      source: 'peaks',
      layout: {
        ...labelLayout(rank),
        'icon-image': ['concat', 'status-', ['get', 'status']],
        // Same sizes the tagged circles had; the icon's inner radius is 10 px.
        'icon-size': ['interpolate', ['linear'], ['zoom'],
          7,  ['/', ['+', 3, ['*', rank, 3.5]], 10],
          10, ['/', ['+', 4.5, ['*', rank, 4.5]], 10],
          14, ['/', ['+', 7.5, ['*', rank, 6]], 10]
        ],
        'icon-padding': 1,
        // Placed in ascending order: status first, then the higher summit.
        //
        // Elevation, not the isolation ranking untagged peaks use. Isolation
        // rewards standing alone, which is what thins 11,000 anonymous dots,
        // but on your own list it reads as arbitrary: Neureuth (1261 m, 7.2 km
        // from higher ground at the edge of the foothills) outranked Rotwand
        // (1884 m, 5.7 km, hemmed in by the Spitzing peaks) and hid it.
        //
        // 9000 is above any Alpine summit, so the subtraction stays positive
        // and below the 10000 that separates one status from the next.
        'symbol-sort-key': ['+',
          ['*', statusRank, 10000],
          ['-', 9000, ['coalesce', ['get', 'ele'], 0]]
        ]
      },
      paint: LABEL_PAINT
    });

    applyFilters();

    // The count of what is on screen changes with zoom, not just with filters.
    map.on('zoomend', renderCounts);
    map.on('moveend', renderCounts);

    // A click on the map that did not land on a peak. The layer handlers below
    // run first and mark the event, so one click never drops two points.
    map.on('click', e => {
      if (RouteDraw.isActive() && !e.originalEvent.peakHandled) {
        RouteDraw.addPoint([e.lngLat.lng, e.lngLat.lat]);
      }
    });

    map.on('click', 'tile-peaks-dots', event => {
      const [lon, lat] = event.features[0].geometry.coordinates;
      const properties = event.features[0].properties;
      event.originalEvent.peakHandled = true;

      if (RouteDraw.isActive()) {
        RouteDraw.addPoint([lon, lat], { name: properties.name, ele: properties.ele });
        return;
      }
      openPicker(tileFeature(lon, lat, properties));
    });

    map.on('mouseenter', 'tile-peaks-dots', () => { map.getCanvas().style.cursor = 'pointer'; });
    map.on('mouseleave', 'tile-peaks-dots', () => { map.getCanvas().style.cursor = RouteDraw.isActive() ? 'crosshair' : ''; });

    for (const layer of ['peaks-dots', 'peaks-tagged']) {
      map.on('click', layer, e => {
        const feature = e.features[0];
        if (RouteDraw.isActive()) {
          e.originalEvent.peakHandled = true;
          // Snap to the summit itself rather than wherever the click landed.
          RouteDraw.addPoint(feature.geometry.coordinates, feature.properties);
          return;
        }
        openPicker(feature);
      });
      map.on('mouseenter', layer, e => {
        map.getCanvas().style.cursor = 'pointer';
        showHover(e.features[0]);
      });
      map.on('mouseleave', layer, () => {
        map.getCanvas().style.cursor = '';
        state.hoverPopup?.remove();
        state.hoverPopup = null;
      });
    }
  });
}

const LABEL_PAINT = {
  'text-color': '#33302c',
  'text-halo-color': '#ffffff',
  'text-halo-width': 1.4
};

function labelLayout(rank) {
  return {
    'text-field': ['concat', ['get', 'name'], '  ', ['to-string', ['get', 'ele']], ' m'],
    'text-font': ['Noto Sans Regular'],
    // Dominant peaks get a larger label as well as an earlier one.
    'text-size': ['interpolate', ['linear'], ['zoom'],
      9,  ['+', 9.5, ['*', rank, 3]],
      14, ['+', 11.5, ['*', rank, 3.5]]
    ],
    'text-offset': [0, 1.1],
    'text-anchor': 'top',
    // A crowded label drops before its dot does.
    'text-optional': true
  };
}

/**
 * One dot per status, drawn on a canvas at 2x so it stays crisp: a 10 px disc
 * in the status colour inside a 2 px white ring, the look the circles had.
 */
function addStatusIcons(map) {
  const radius = 20, ring = 4, size = 2 * (radius + ring);
  for (const key of TAGGED) {
    const canvas = document.createElement('canvas');
    canvas.width = canvas.height = size;
    const ctx = canvas.getContext('2d');
    for (const [r, color] of [[radius + ring, '#ffffff'], [radius, STATUSES[key].color]]) {
      ctx.beginPath();
      ctx.arc(size / 2, size / 2, r, 0, 2 * Math.PI);
      ctx.fillStyle = color;
      ctx.fill();
    }
    map.addImage(`status-${key}`, ctx.getImageData(0, 0, size, size), { pixelRatio: 2 });
  }
}

/**
 * The basemap's peaks, under ours so our own dots always win a collision, and
 * hollow so the two never read as the same thing.
 */
function addTilePeakLayers(map) {
  const visible = tilePeaksOn() ? 'visible' : 'none';

  map.addLayer({
    id: 'tile-peaks-dots',
    type: 'circle',
    source: TILE_PEAKS.source,
    'source-layer': TILE_PEAKS.sourceLayer,
    layout: { visibility: visible },
    paint: {
      'circle-radius': ['interpolate', ['linear'], ['zoom'], 8, 2, 14, 4],
      'circle-color': 'rgba(255, 255, 255, 0.9)',
      'circle-stroke-color': '#6b5ca5',
      'circle-stroke-width': 1.5
    }
  });

  map.addLayer({
    id: 'tile-peaks-labels',
    type: 'symbol',
    source: TILE_PEAKS.source,
    'source-layer': TILE_PEAKS.sourceLayer,
    layout: {
      visibility: visible,
      'text-field': ['concat', ['get', 'name'], '  ', ['to-string', ['get', 'ele']], ' m'],
      'text-font': ['Noto Sans Regular'],
      'text-size': ['interpolate', ['linear'], ['zoom'], 9, 9, 14, 11],
      'text-offset': [0, 1],
      'text-anchor': 'top',
      'text-optional': true,
      // rank 1 is the one people have heard of, so it is placed first.
      'symbol-sort-key': ['coalesce', ['get', 'rank'], 5]
    },
    paint: {
      'text-color': '#4a4160',
      'text-halo-color': '#ffffff',
      'text-halo-width': 1.3
    }
  });

  applyTilePeakFilter();
}

const tilePeaksOn = () => {
  try {
    return localStorage.getItem(TILE_PEAKS.key) === 'on';
  } catch {
    return false;
  }
};

function setTilePeaks(on) {
  try {
    localStorage.setItem(TILE_PEAKS.key, on ? 'on' : 'off');
  } catch { /* private browsing: the switch still works for this visit */ }

  for (const id of ['tile-peaks-dots', 'tile-peaks-labels']) {
    if (state.map?.getLayer(id)) state.map.setLayoutProperty(id, 'visibility', on ? 'visible' : 'none');
  }
  renderCounts();
}

/**
 * The elevation sliders apply here too; the detail slider decides how deep into
 * the ranks to go, since rank is all the tiles offer in place of isolation.
 * Country and status filters cannot: a tile peak has neither.
 */
function applyTilePeakFilter() {
  if (!state.map?.getLayer('tile-peaks-dots')) return;
  const { minEle, detail } = state.filters;

  const filter = ['all',
    ['>=', ['coalesce', ['get', 'ele'], 0], minEle],
    ['<=', ['coalesce', ['get', 'ele'], 0], ceiling()],
    ['<=', ['coalesce', ['get', 'rank'], 5],
      ['+', ['interpolate', ['linear'], ['zoom'], 8, 1, 11, 3, 13, 5], detail]]
  ];
  for (const id of ['tile-peaks-dots', 'tile-peaks-labels']) state.map.setFilter(id, filter);
}

function refreshSource() {
  state.map?.getSource('peaks')?.setData(collection());
}

/** The upper slider, or no ceiling at all when it sits at the top. */
const ceiling = () =>
  state.filters.maxEle >= (state.eleRange?.max ?? Infinity) ? 99999 : state.filters.maxEle;

function applyFilters() {
  if (!state.map?.getLayer('peaks-dots')) return;
  const { minEle, statuses, countries, search } = state.filters;

  const filter = ['all',
    ['>=', ['get', 'ele'], minEle],
    ['<=', ['get', 'ele'], ceiling()],
    ['in', ['get', 'status'], ['literal', [...statuses]]]
  ];
  // country is "AT", "DE" or "AT/DE" for a border summit — a substring test
  // matches the border case under either country.
  if (countries.size) {
    filter.push(['any', ...[...countries].map(c => ['in', c, ['get', 'country']])]);
  }
  if (search.trim()) {
    filter.push(['in', search.trim().toLowerCase(), ['downcase', ['coalesce', ['get', 'name'], '']]]);
  }

  const untagged = [...filter, ['==', ['get', 'status'], 'none'], zoomRankFilter()];
  state.map.setFilter('peaks-dots', untagged);
  state.map.setFilter('peaks-labels', untagged);
  state.map.setFilter('peaks-tagged', [...filter, ['!=', ['get', 'status'], 'none']]);
  applyTilePeakFilter();
  renderCounts();
}

/**
 * Show an untagged peak once the map reaches its `minZoom`, shifted by the
 * detail slider. MapLibre does allow `zoom` inside a filter; it is evaluated
 * at integer zoom levels, which is all this needs. PEAK_MIN_ZOOM defaults to 0,
 * so a snapshot generated before minZoom existed shows everything rather than
 * failing on null and hiding every peak.
 */
function zoomRankFilter() {
  return ['<=', ['-', PEAK_MIN_ZOOM, state.filters.detail], ['zoom']];
}

/**
 * Mirrors the layer filters for the panel counters. Tagged peaks pass at any
 * zoom; whether one actually fits on screen is up to collision, which the
 * counter cannot see.
 */
function passesZoomRank(properties, zoom) {
  if (properties.status !== 'none') return true;
  return (properties.minZoom ?? 0) - state.filters.detail <= zoom;
}

function visibleFeatures() {
  const { minEle, statuses, countries, search } = state.filters;
  const needle = search.trim().toLowerCase();
  const zoom = Math.floor(state.map?.getZoom() ?? 9);
  return state.features.filter(f => {
    const p = f.properties;
    if (p.ele < minEle || p.ele > ceiling()) return false;
    if (!statuses.has(p.status)) return false;
    if (countries.size && ![...countries].some(c => p.country.includes(c))) return false;
    if (needle && !(p.name ?? '').toLowerCase().includes(needle)) return false;
    if (!passesZoomRank(p, zoom)) return false;
    return true;
  });
}

// ─── Status editing ───────────────────────────────────────────────────────────

/**
 * `extra` is merged into the entry — the outing form passes the walk's date, so
 * tagging a summit from a dated outing records when it was climbed rather than
 * only that it was.
 */
async function setStatus(id, status, extra = {}) {
  const key = String(id);
  const feature = state.byId.get(key);
  if (!feature) return;

  const entry = status === 'none'
    // Keep a tombstone: the committed baseline would otherwise put it back.
    ? { status: 'none', name: feature.properties.name, ele: feature.properties.ele }
    : {
        ...(PeakStore.get(key) ?? {}),
        status,
        name: feature.properties.name,
        ele: feature.properties.ele,
        country: feature.properties.country === '??' ? null : feature.properties.country,
        // Where it is and where it came from, so the peak survives the
        // snapshot it was found in.
        lon: feature.geometry.coordinates[0],
        lat: feature.geometry.coordinates[1],
        source: feature.properties.source ?? 'osm',
        updated: new Date().toISOString().slice(0, 10),
        ...extra
      };

  // A peak from the tiles arrives without a country; ask for one so the filter
  // and the stats stay honest.
  if (status !== 'none' && !entry.country && entry.lat != null) {
    const code = await resolveCountry(entry.lon, entry.lat);
    if (code) {
      entry.country = code;
      feature.properties.country = code;
    }
  }

  if (!(await PeakStore.set(key, entry))) {
    flash(`Could not save ${feature.properties.name} — try again`, true);
    return;
  }

  feature.properties.status = status;
  refreshSource();
  applyFilters();
  renderTaggedList();
}

/**
 * A peak clicked in the basemap's own layer, as a feature of ours.
 *
 * If the snapshot already holds that summit — the two sources overlap all over
 * the Alps — its own feature is used instead, so tagging keeps the OSM id and
 * a peak never ends up on the list twice under two identities.
 */
function tileFeature(lon, lat, properties) {
  const existing = nearestFeature([lon, lat], 120);
  if (existing) return existing;

  const id = idFromPosition(lon, lat);
  const key = String(id);
  const known = state.byId.get(key);
  if (known) return known;

  const feature = {
    type: 'Feature',
    id,
    geometry: { type: 'Point', coordinates: [lon, lat] },
    properties: {
      id,
      name: properties.name ?? 'Unnamed peak',
      ele: properties.ele ?? 0,
      country: '??',
      source: 'tile',
      minZoom: 0,
      status: state.statuses.get(key)?.status ?? 'none'
    }
  };
  state.features.push(feature);
  state.byId.set(key, feature);
  refreshSource();
  return feature;
}

/** The nearest peak we already know about, within a few paces. */
function nearestFeature(point, metres) {
  const degrees = metres / 111000 * 2;
  let best = null, bestDistance = Infinity;
  for (const feature of state.features) {
    const [lon, lat] = feature.geometry.coordinates;
    if (Math.abs(lon - point[0]) > degrees || Math.abs(lat - point[1]) > degrees) continue;
    const away = RouteStore.metresBetween(point, [lon, lat]);
    if (away < bestDistance && away <= metres) { best = feature; bestDistance = away; }
  }
  return best;
}

/** Everything actually tagged — tombstones and untagged peaks excluded. */
function taggedEntries() {
  const entries = [];
  for (const [id, entry] of state.statuses) {
    if (!entry || entry.status === 'none') continue;
    const feature = state.byId.get(id);
    entries.push({ id, entry, feature });
  }
  return entries.sort((a, b) =>
    TAGGED.indexOf(a.entry.status) - TAGGED.indexOf(b.entry.status) ||
    (b.feature?.properties.ele ?? 0) - (a.feature?.properties.ele ?? 0)
  );
}

// ─── Popups ───────────────────────────────────────────────────────────────────

function showHover(feature) {
  const p = feature.properties;
  state.hoverPopup?.remove();
  state.hoverPopup = new maplibregl.Popup({ closeButton: false, closeOnClick: false, offset: 10, className: 'peak-hover' })
    .setLngLat(feature.geometry.coordinates)
    .setHTML(`<strong>${escapeHtml(p.name)}</strong> · ${p.ele} m`)
    .addTo(state.map);
}

function openPicker(feature) {
  const p = feature.properties;
  const id = String(p.id);
  const current = state.statuses.get(id)?.status ?? 'none';

  const el = document.createElement('div');
  el.className = 'peak-picker';
  el.innerHTML = `
    <h3>${escapeHtml(p.name)}</h3>
    <p class="peak-picker-meta">
      ${p.ele} m${p.prominence ? ` · ${p.prominence} m prominence` : ''}
      ${p.country && p.country !== '??' ? ` · ${p.country.split('/').map(c => COUNTRY_NAMES[c] ?? c).join(' / ')}` : ''}
    </p>
    <p class="peak-picker-meta">${describeIsolation(p.isolation)}</p>
    <div class="peak-picker-options"></div>
    <div class="peak-routes" id="peak-routes" data-peak-id="${id}"></div>
    <div class="peak-picker-links">
      <a href="https://www.openstreetmap.org/node/${p.id}" target="_blank" rel="noopener">OSM</a>
      ${p.wikipedia ? `<a href="https://${wikipediaHost(p.wikipedia)}" target="_blank" rel="noopener">Wikipedia</a>` : ''}
      <a href="https://www.google.com/maps/dir/?api=1&destination=${feature.geometry.coordinates[1]},${feature.geometry.coordinates[0]}" target="_blank" rel="noopener">Directions</a>
      <button type="button" id="peak-add-route">Add outing</button>
      <button type="button" id="peak-draw-route">Draw from here</button>
    </div>
  `;

  const options = el.querySelector('.peak-picker-options');
  for (const key of [...TAGGED, 'none']) {
    const { label, color, hint } = STATUSES[key];
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = `peak-option${key === current ? ' is-current' : ''}`;
    btn.style.setProperty('--option-color', color);
    btn.title = hint;
    btn.textContent = label;
    btn.addEventListener('click', async () => {
      await setStatus(id, key);
      state.popup?.remove();
      flash(key === 'none' ? `${p.name} cleared` : `${p.name} → ${label}`);
    });
    options.appendChild(btn);
  }

  state.popup?.remove();
  // anchor 'top' — the popup hangs below the peak — is not a look but a
  // rendering fix. MapLibre rounds the popup's position, then adds the
  // anchor's own translate: 'bottom' means translateY(-100%) of a box whose
  // height is fractional (rem padding, line boxes), which lands the text on a
  // half pixel and blurs every glyph. 'top' translates by 0 vertically, and
  // the 320 px content width in the stylesheet keeps -50% whole horizontally.
  state.popup = new maplibregl.Popup({ offset: 14, maxWidth: '320px', className: 'peak-popup', anchor: 'top' })
    .setLngLat(feature.geometry.coordinates)
    .setDOMContent(el)
    .addTo(state.map);

  el.querySelector('#peak-add-route').addEventListener('click', () => RouteForm.open({ peak: feature }));
  el.querySelector('#peak-draw-route').addEventListener('click', () => {
    RouteDraw.start();
    RouteDraw.addPoint(feature.geometry.coordinates, feature.properties);
  });
  renderPeakRoutes(el.querySelector('#peak-routes'), id);
  // After the outings are in, not before: the popup is taller by then, and a
  // measurement taken too early pans by less than it needs to.
  requestAnimationFrame(keepPopupOnScreen);

  // Clicking a peak you have walked shows the walk, which is the whole point
  // of having the tracks here.
  const drawnNow = RouteStore.forPeak(id).filter(route => drawTrack(route));
  if (drawnNow.length) fitTracks(drawnNow);
}

/**
 * A popup anchored below its peak runs off the bottom when the peak is low on
 * screen, off the side when it is near an edge, and under the panel when it is
 * behind it — and a fixed anchor never flips. So move the map instead, which
 * keeps the peak, its popup and the whole-pixel rounding all intact.
 */
function keepPopupOnScreen() {
  const node = document.querySelector('.peak-popup');
  if (!node || !state.map) return;

  const popup = node.getBoundingClientRect();
  const canvas = state.map.getCanvas().getBoundingClientRect();
  const panel = document.querySelector('.peaks-panel');
  const panelBox = panel && !document.body.classList.contains('peaks-panel-collapsed')
    ? panel.getBoundingClientRect()
    : null;

  // The clear area is the canvas minus the floating panel and a margin.
  const margin = 12;
  const clear = {
    left: Math.max(canvas.left, panelBox ? panelBox.right : canvas.left) + margin,
    right: canvas.right - margin,
    bottom: canvas.bottom - margin
  };

  // Positive values pan the map so the popup comes back into the clear.
  let x = 0;
  if (popup.right > clear.right) x = popup.right - clear.right;
  if (popup.left - x < clear.left) x = popup.left - clear.left;
  const y = Math.max(0, popup.bottom - clear.bottom);

  if (x || y) state.map.panBy([x, y], { duration: 250 });
}

/**
 * Brings tracks into the part of the map nothing is covering. The popup opens
 * above the peak and the panel sits down the left, so a track fitted to the
 * whole canvas lands underneath one or the other; these paddings keep it in
 * the clear. Clamped to the canvas, since MapLibre throws if padding exceeds
 * the space it has.
 */
function fitTracks(routes = [...state.drawn.values()].map(f => RouteStore.get(f.properties.id))) {
  const map = state.map;
  const tracks = routes.filter(route => route?.track);
  if (!map || !tracks.length) return;

  const bounds = new maplibregl.LngLatBounds();
  for (const route of tracks) {
    for (const point of RouteStore.decode(route.track)) bounds.extend(point);
  }

  const { width, height } = map.getCanvas().getBoundingClientRect();
  const panelOpen = !document.body.classList.contains('peaks-panel-collapsed');
  const clamp = (value, limit) => Math.max(20, Math.min(value, limit));

  map.fitBounds(bounds, {
    padding: {
      top: clamp(60, height * 0.15),
      bottom: clamp(320, height * 0.42),   // the popup hangs here
      left: clamp(panelOpen ? 350 : 60, width * 0.4),
      right: clamp(60, width * 0.15)
    },
    maxZoom: 14.5,
    duration: 700
  });
}

// ─── Routes on a peak ─────────────────────────────────────────────────────────

function renderPeakRoutes(el, peakId) {
  if (!el) return;

  if (!RouteStore.available()) {
    el.innerHTML = '<p class="peak-routes-empty">Sign in to keep tracks, photos and notes against a peak.</p>';
    return;
  }

  const routes = RouteStore.forPeak(peakId);
  if (!routes.length) {
    el.innerHTML = '<p class="peak-routes-empty">No outing recorded here yet.</p>';
    return;
  }

  el.innerHTML = routes.map(route => `
    <details class="peak-route" data-id="${route.id}">
      <summary>
        <span class="peak-route-dot" style="background:${STATUSES[route.kind]?.color ?? '#555'}"></span>
        <span class="peak-route-title">${escapeHtml(route.title)}</span>
        <span class="peak-route-date">${route.date ? formatStatDate(route.date) : STATUSES[route.kind]?.label ?? ''}</span>
      </summary>
      <p class="peak-route-stats">${describeRoute(route)}</p>
      ${route.description ? `<p class="peak-route-note">${escapeHtml(route.description)}</p>` : ''}
      ${route.notes ? `<p class="peak-route-note">${escapeHtml(route.notes)}</p>` : ''}
      ${route.peaks?.length > 1
        ? `<p class="peak-route-note">Also: ${route.peaks.filter(p => String(p.peak_id) !== String(peakId)).map(p => escapeHtml(p.name ?? p.peak_id)).join(', ')}</p>`
        : ''}
      <div class="peak-picker-links">
        ${route.strava_url ? `<a href="${escapeHtml(route.strava_url)}" target="_blank" rel="noopener">Strava</a>` : ''}
        ${route.photos_url ? `<a href="${escapeHtml(route.photos_url)}" target="_blank" rel="noopener">Photos</a>` : ''}
        ${(route.links ?? []).map(l => `<a href="${escapeHtml(l.url)}" target="_blank" rel="noopener">${escapeHtml(l.label)}</a>`).join('')}
        ${route.track ? `<button type="button" class="peak-route-zoom">Zoom to track</button>` : ''}
        <button type="button" class="peak-route-edit">Edit</button>
      </div>
    </details>
  `).join('');

  // Expanding an outing makes the popup taller, which can push it off screen.
  el.querySelectorAll('.peak-route').forEach(details => {
    details.addEventListener('toggle', () => requestAnimationFrame(keepPopupOnScreen));
  });

  el.querySelectorAll('.peak-route-edit').forEach(button => {
    button.addEventListener('click', () => {
      RouteForm.open({ route: RouteStore.get(button.closest('.peak-route').dataset.id) });
    });
  });

  el.querySelectorAll('.peak-route-zoom').forEach(button => {
    button.addEventListener('click', () => {
      const route = RouteStore.get(button.closest('.peak-route').dataset.id);
      drawTrack(route);
      fitTracks([route]);
    });
  });
}

/** "12.3 km · 1216 m up · 6:30 h · Hard", skipping whatever is missing. */
function describeRoute(route) {
  const bits = [];
  if (route.distance_m) bits.push(`${(route.distance_m / 1000).toFixed(1)} km`);
  if (route.ascent_m) bits.push(`${route.ascent_m} m up`);
  if (route.moving_seconds) {
    const hours = Math.floor(route.moving_seconds / 3600);
    const minutes = Math.round((route.moving_seconds % 3600) / 60);
    bits.push(`${hours}:${String(minutes).padStart(2, '0')} h`);
  }
  if (route.difficulty) bits.push(escapeHtml(route.difficulty));
  if (route.location) bits.push(escapeHtml(route.location));
  return bits.join(' · ') || 'No stats recorded';
}

// ─── Tracks on the map ────────────────────────────────────────────────────────

const trackCollection = () => ({
  type: 'FeatureCollection',
  features: [...state.drawn.values()]
});

function drawTrack(route) {
  if (!route?.track) return false;
  // An edited route is redrawn rather than skipped, so a replaced track shows.
  const isNew = !state.drawn.has(route.id);
  state.drawn.set(route.id, {
    type: 'Feature',
    properties: { id: route.id, kind: route.kind, title: route.title },
    geometry: { type: 'LineString', coordinates: RouteStore.decode(route.track) }
  });
  state.map?.getSource('tracks')?.setData(trackCollection());
  renderTrackBar();
  return isNew;
}

/** Takes one track off the map, for a route that has just been deleted. */
function undrawTrack(id) {
  if (!state.drawn.delete(id)) return;
  state.map?.getSource('tracks')?.setData(trackCollection());
  renderTrackBar();
}

function clearTracks() {
  state.drawn.clear();
  state.map?.getSource('tracks')?.setData(trackCollection());
  renderTrackBar();
}

/** Only present while something is drawn — otherwise it is a row saying zero. */
function renderTrackBar() {
  const el = document.getElementById('peaks-tracks');
  if (!el) return;
  const count = state.drawn.size;
  el.hidden = count === 0;
  if (!count) return;
  el.innerHTML = `
    <span>${count} track${count === 1 ? '' : 's'} on the map</span>
    <button type="button" id="peaks-clear-tracks">Clear</button>
  `;
  el.querySelector('#peaks-clear-tracks').addEventListener('click', clearTracks);
}

/**
 * Says in words what the isolation figure means, since it is the thing deciding
 * whether a peak is treated as a mountain or as part of its bigger neighbour.
 */
function describeIsolation(metres) {
  if (metres === null || metres === undefined) return 'Highest peak in the dataset';
  if (metres < 500) return `A secondary summit — higher ground only ${Math.round(metres)} m away`;
  if (metres < 2000) return `${(metres / 1000).toFixed(1)} km to higher ground`;
  return `${Math.round(metres / 1000)} km to higher ground — a dominant peak`;
}

const wikipediaHost = tag => {
  const [lang, ...rest] = String(tag).split(':');
  return rest.length
    ? `${lang}.wikipedia.org/wiki/${encodeURIComponent(rest.join(':'))}`
    : `en.wikipedia.org/wiki/${encodeURIComponent(tag)}`;
};

// ─── Panel ────────────────────────────────────────────────────────────────────

function buildPanel(peaks) {
  // Most peaks first, so the list starts where the walking is; '??' last,
  // whatever its count, because it is a fallback rather than a place.
  const counts = new Map();
  for (const f of state.features) {
    for (const code of f.properties.country.split('/')) {
      counts.set(code, (counts.get(code) ?? 0) + 1);
    }
  }
  const countries = [...counts.keys()].sort((a, b) =>
    (a === '??') - (b === '??') || counts.get(b) - counts.get(a)
  );

  const { minEle, maxEle } = state.filters;

  document.getElementById('peaks-panel').innerHTML = `
    <header class="peaks-panel-head">
      <h2>Peak Planner</h2>
      <p>Click any peak to mark it.</p>
    </header>

    <div id="peaks-counts" class="peaks-counts"></div>
    <dl id="peaks-stats" class="peaks-stats"></dl>
    <div id="peaks-tracks" class="peaks-tracks" hidden></div>
    <section id="peaks-draw" class="peaks-draw" hidden></section>
    <div class="peaks-buttons">
      <button type="button" id="peaks-draw-start">Draw a route</button>
    </div>

    <section class="peaks-filters">
      <h3>Filters</h3>

      <label class="peaks-field">
        <span>Search</span>
        <input type="search" id="peaks-search" placeholder="Peak name…" autocomplete="off">
      </label>

      <label class="peaks-field">
        <span>Detail — <output id="peaks-detail-out">balanced</output></span>
        <input type="range" id="peaks-detail" min="-2" max="3" step="1" value="0">
        <small class="peaks-hint">Secondary summits stay hidden until you zoom in. Slide right to reveal them sooner.</small>
      </label>

      <label class="peaks-field">
        <span>Minimum elevation — <output id="peaks-min-out">${minEle} m</output></span>
        <input type="range" id="peaks-min" min="${minEle}" max="${maxEle}" step="50" value="${minEle}">
      </label>

      <label class="peaks-field">
        <span>Maximum elevation — <output id="peaks-max-out">no limit</output></span>
        <input type="range" id="peaks-max" min="${minEle}" max="${maxEle}" step="50" value="${maxEle}">
      </label>

      <fieldset class="peaks-field">
        <legend>Status</legend>
        <div class="peaks-checks" id="peaks-status-filters">
          ${[...TAGGED, 'none'].map(key => `
            <label class="peaks-check">
              <input type="checkbox" value="${key}" checked>
              <span class="peaks-swatch" style="background:${STATUSES[key].color}"></span>
              ${STATUSES[key].label}
            </label>
          `).join('')}
        </div>
      </fieldset>

      <label class="peaks-check peaks-check--switch">
        <input type="checkbox" id="peaks-tile-toggle">
        <span>More peaks, worldwide</span>
      </label>
      <small class="peaks-hint">
        Every peak the basemap knows — the Andes, the Himalaya, anywhere. They carry
        no country, so a country filter hides them.
      </small>

      <fieldset class="peaks-field">
        <legend>Country</legend>
        <div class="peaks-checks" id="peaks-country-filters">
          ${countries.map(code => `
            <label class="peaks-check">
              <input type="checkbox" value="${code}">
              ${COUNTRY_NAMES[code] ?? code}
              <span class="peaks-check-count">${counts.get(code)}</span>
            </label>
          `).join('')}
        </div>
      </fieldset>
    </section>

    <section class="peaks-actions">
      <h3>Your list</h3>
      <div id="peaks-tagged" class="peaks-tagged"></div>
      <p id="peaks-save-state" class="peaks-note"></p>
      <div id="peaks-account" class="peaks-account"></div>

      <details class="peaks-advanced">
        <summary>Backup &amp; sharing</summary>
        <p class="peaks-note">
          A file of your tagged peaks — to keep a copy, move the list to another
          account, or send someone your plans. Importing merges the file in; it
          overwrites a peak only if the file has a status for it.
        </p>
        <div class="peaks-buttons">
          <button type="button" id="peaks-add-route" hidden>Add outing</button>
          <button type="button" id="peaks-import-hikes" hidden>Import old hikes</button>
        </div>
        <div class="peaks-buttons">
          <button type="button" id="peaks-export">Export JSON</button>
          <label class="peaks-import">
            Import
            <input type="file" id="peaks-import" accept="application/json,.json" hidden>
          </label>
        </div>
      </details>
      <p class="peaks-note peaks-source">
        ${state.features.length} peaks · snapshot ${peaks.generated ?? '—'} ·
        ${peaks.attribution ?? '© OpenStreetMap contributors'}
      </p>
    </section>
  `;

  document.getElementById('peaks-draw-start').addEventListener('click', () => RouteDraw.start());

  wirePanel();
  renderTaggedList();
  renderAccount();
}

// ─── Importing the repo's own hikes ───────────────────────────────────────────

/**
 * Pulls the folders under gpx/ into the account: one route each, its stats read
 * from info.json where they exist and measured off the track where they do not,
 * linked to whichever summits the walk actually passed over.
 *
 * Idempotent by folder name — a route remembers the folder it came from, so
 * running this twice does not import anything twice.
 */
async function importRepoHikes(button) {
  if (!RouteStore.available()) return flash('Sign in first — routes live in your account', true);

  button.disabled = true;
  const original = button.textContent;
  let added = 0, skipped = 0, failed = 0;

  try {
    const index = await fetch('data/hikes.json').then(r => r.json());
    const folders = [
      ...(index.completed ?? []).map(folder => ['done', folder]),
      ...(index.planned ?? []).map(folder => ['planned', folder])
    ];

    for (const [kind, folder] of folders) {
      const source = `gpx/${folder}`;
      if (RouteStore.hasSource(source)) { skipped++; continue; }

      button.textContent = `Importing ${folder}…`;
      try {
        const info = await fetch(`${source}/info.json`).then(r => (r.ok ? r.json() : {}));
        const gpx = await fetch(`${source}/track.gpx`).then(r => (r.ok ? r.text() : null));
        const parsed = gpx ? RouteStore.readGpx(gpx) : null;

        await RouteStore.save({
          kind,
          source,
          title: info.title || folder,
          // A planned walk has no date; the file's own timestamps beat a blank one.
          date: info.date || parsed?.date || null,
          location: info.location || null,
          country: /^[A-Z]{2}$/.test(info.flag ?? '') ? info.flag : null,
          description: info.description || null,
          difficulty: info.difficulty || null,
          // What you recorded wins; the track fills the gaps.
          distance_m: parseDistance(info.distance) ?? parsed?.distance_m ?? null,
          ascent_m: parseMetres(info.elevation) ?? parsed?.ascent_m ?? null,
          moving_seconds: parseDuration(info.movingTime) ?? parsed?.moving_seconds ?? null,
          photos_url: info.photos || null,
          track: parsed?.track ?? null,
          track_points: parsed?.track_points ?? null,
          bounds: parsed?.bounds ?? null
        }, parsed ? peaksAlong(parsed.fullPoints) : []);
        added++;
      } catch (err) {
        console.error(`[routes] ${source} failed:`, err);
        failed++;
      }
    }
  } catch (err) {
    console.error('[routes] import failed:', err);
    flash('Could not read data/hikes.json', true);
  }

  button.disabled = false;
  button.textContent = original;
  renderTaggedList();
  flash(`Imported ${added}${skipped ? `, ${skipped} already there` : ''}${failed ? `, ${failed} failed` : ''}`, failed > 0);
}

/**
 * The summits a walk went over: peaks within 80 m of the recorded line. Wide
 * enough for a GPS fix on a summit block, tight enough that a peak passed on
 * the far side of the valley does not count as climbed.
 */
function peaksAlong(points, metres = 80) {
  const lons = points.map(p => p[0]), lats = points.map(p => p[1]);
  // A degree of latitude is ~111 km; pad the box so nothing on the edge is missed.
  const pad = metres / 111000 * 2;
  const box = [Math.min(...lons) - pad, Math.min(...lats) - pad, Math.max(...lons) + pad, Math.max(...lats) + pad];

  const found = [];
  for (const feature of state.features) {
    const [lon, lat] = feature.geometry.coordinates;
    if (lon < box[0] || lon > box[2] || lat < box[1] || lat > box[3]) continue;
    const near = points.some(p => RouteStore.metresBetween(p, [lon, lat]) <= metres);
    if (near) found.push({ peak_id: feature.properties.id, name: feature.properties.name, ele: feature.properties.ele });
  }
  return found;
}

/** "12.3 km" → 12300. Also takes a bare number, and metres. */
function parseDistance(text) {
  const value = parseFloat(String(text ?? '').replace(',', '.'));
  if (!Number.isFinite(value)) return null;
  return /\bm\b/.test(String(text)) && !/km/.test(String(text))
    ? Math.round(value)
    : Math.round(value * 1000);
}

/** "1216 m" → 1216. */
function parseMetres(text) {
  const value = parseFloat(String(text ?? '').replace(',', '.'));
  return Number.isFinite(value) ? Math.round(value) : null;
}

/** "6:30 h" → 23400 seconds. */
function parseDuration(text) {
  const match = String(text ?? '').match(/(\d+):(\d{2})/);
  if (match) return Number(match[1]) * 3600 + Number(match[2]) * 60;
  const hours = parseFloat(String(text ?? '').replace(',', '.'));
  return Number.isFinite(hours) ? Math.round(hours * 3600) : null;
}

function wirePanel() {
  const tileToggle = document.getElementById('peaks-tile-toggle');
  tileToggle.checked = tilePeaksOn();
  tileToggle.addEventListener('change', () => {
    setTilePeaks(tileToggle.checked);
    if (tileToggle.checked && state.filters.countries.size) {
      flash('Worldwide peaks have no country — clear the country filter to see them', true);
    }
  });

  const search = document.getElementById('peaks-search');
  search.addEventListener('input', () => {
    state.filters.search = search.value;
    applyFilters();
  });

  const min = document.getElementById('peaks-min');
  const max = document.getElementById('peaks-max');
  const minOut = document.getElementById('peaks-min-out');
  const maxOut = document.getElementById('peaks-max-out');

  min.addEventListener('input', () => {
    if (Number(min.value) > Number(max.value)) max.value = min.value;
    state.filters.minEle = Number(min.value);
    state.filters.maxEle = Number(max.value);
    minOut.textContent = `${min.value} m`;
    // At the top the slider stops being a ceiling, so it should stop claiming
    // to be one: there are peaks above the snapshot's highest.
    maxOut.textContent = Number(max.value) >= state.eleRange.max ? 'no limit' : `${max.value} m`;
    applyFilters();
  });

  max.addEventListener('input', () => {
    if (Number(max.value) < Number(min.value)) min.value = max.value;
    state.filters.minEle = Number(min.value);
    state.filters.maxEle = Number(max.value);
    minOut.textContent = `${min.value} m`;
    // At the top the slider stops being a ceiling, so it should stop claiming
    // to be one: there are peaks above the snapshot's highest.
    maxOut.textContent = Number(max.value) >= state.eleRange.max ? 'no limit' : `${max.value} m`;
    applyFilters();
  });

  document.getElementById('peaks-status-filters').addEventListener('change', e => {
    const box = e.target;
    state.filters.statuses[box.checked ? 'add' : 'delete'](box.value);
    applyFilters();
  });

  document.getElementById('peaks-country-filters').addEventListener('change', e => {
    const box = e.target;
    state.filters.countries[box.checked ? 'add' : 'delete'](box.value);
    applyFilters();
  });

  const detail = document.getElementById('peaks-detail');
  const detailOut = document.getElementById('peaks-detail-out');
  const DETAIL_LABELS = { '-2': 'major peaks only', '-1': 'sparse', 0: 'balanced', 1: 'more', 2: 'dense', 3: 'everything' };
  detail.addEventListener('input', () => {
    state.filters.detail = Number(detail.value);
    detailOut.textContent = DETAIL_LABELS[detail.value] ?? detail.value;
    applyFilters();
  });

  document.getElementById('peaks-export').addEventListener('click', exportStatuses);
  document.getElementById('peaks-import').addEventListener('change', importStatuses);

  const toggle = document.getElementById('peaks-panel-toggle');
  toggle.addEventListener('click', () => {
    const collapsed = document.body.classList.toggle('peaks-panel-collapsed');
    toggle.setAttribute('aria-expanded', String(!collapsed));
    toggle.title = collapsed ? 'Show the panel' : 'Hide the panel';
    toggle.firstElementChild.textContent = collapsed ? '›' : '‹';
    // The map keeps its full size underneath; only the overlay moves, so there
    // is nothing to resize — but the centre of what you can see has shifted.
    state.map?.easeTo({ duration: 200 });
  });
}

function renderCounts() {
  const el = document.getElementById('peaks-counts');
  if (!el) return;

  const visible = visibleFeatures();
  const counts = Object.fromEntries(TAGGED.map(s => [s, 0]));
  for (const { entry } of taggedEntries()) counts[entry.status]++;

  el.innerHTML = `
    <div class="peaks-count peaks-count--total">
      <span class="peaks-count-value">${visible.length}</span>
      <span class="peaks-count-label">peaks shown</span>
    </div>
    ${TAGGED.map(key => `
      <div class="peaks-count">
        <span class="peaks-count-value" style="color:${STATUSES[key].color}">${counts[key]}</span>
        <span class="peaks-count-label">${STATUSES[key].label}</span>
      </div>
    `).join('')}
  `;
}

/**
 * What the done list adds up to — the part of the old Summits tab worth
 * keeping, next to the peaks it is counting.
 *
 * Elevation comes from the entry first and the snapshot second, so a peak that
 * a later snapshot drops still counts.
 */
function renderStats() {
  const el = document.getElementById('peaks-stats');
  if (!el) return;

  const tagged = taggedEntries();
  const eleOf = ({ entry, feature }) => entry.ele ?? feature?.properties.ele ?? 0;
  const done = tagged.filter(t => t.entry.status === 'done');

  if (!done.length) {
    el.innerHTML = '<p class="peaks-empty">Mark a peak done and your record appears here.</p>';
    return;
  }

  const highest = done.reduce((a, b) => (eleOf(b) > eleOf(a) ? b : a));
  const countries = new Set(done.flatMap(t =>
    (t.entry.country ?? t.feature?.properties.country ?? '').split('/').filter(c => c && c !== '??')
  ));
  const stacked = done.reduce((sum, t) => sum + eleOf(t), 0);
  // Both sources, because neither is complete on its own: a status carries a
  // date only when something put one there (8 of 19 here, seeded from the old
  // summits.json), while every outing has one. Reading statuses alone reported
  // the last dated tag as the last climb, which is how a walk in September
  // showed up as August.
  const climbed = [
    ...done.filter(t => t.entry.date).map(t => t.entry.date),
    ...RouteStore.all().filter(route => route.kind === 'done' && route.date).map(route => route.date)
  ].sort();
  const planned = tagged.filter(t => t.entry.status === 'planned');
  const nextUp = planned.length ? planned.reduce((a, b) => (eleOf(b) > eleOf(a) ? b : a)) : null;

  // No summit count here: the Done counter sits directly above this.
  const rows = [
    ['Highest', `${escapeHtml(highest.entry.name ?? '')} · ${eleOf(highest)} m`],
    // Sorted by name, not by code: AT, CH, DE reads as unsorted once it says
    // Austria, Switzerland, Germany.
    ['Countries', [...countries].map(c => COUNTRY_NAMES[c] ?? c).sort().join(', ') || '—'],
    // Every summit stacked on top of the last — a number with no practical
    // meaning that is nonetheless the one people want to know.
    ['Stacked', `${stacked.toLocaleString('en-GB')} m`]
  ];
  if (climbed.length) rows.push(['Last climbed', formatStatDate(climbed.at(-1))]);
  if (nextUp) rows.push(['Biggest plan', `${escapeHtml(nextUp.entry.name ?? '')} · ${eleOf(nextUp)} m`]);

  el.innerHTML = rows.map(([label, value]) => `
    <div class="peaks-stat">
      <dt>${label}</dt>
      <dd>${value}</dd>
    </div>
  `).join('');
}

/** "2025-06-15" → "15 Jun 2025", falling back to the raw string. */
function formatStatDate(iso) {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return escapeHtml(iso);
  return date.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
}

/**
 * Says where tagging a peak actually writes. Signed in, that is the account.
 * Signed out it is localStorage, which nobody else sees until the file is
 * exported and committed, so the least this can do is not pretend it is saved.
 */
function renderSaveState() {
  const el = document.getElementById('peaks-save-state');
  if (!el) return;

  const changed = PeakStore.pendingCount();
  el.classList.toggle('is-unsaved', changed > 0 && !PeakStore.isShared());

  if (PeakStore.isShared()) {
    el.innerHTML = `Saved to your account — ${PeakStore.describe()}.`;
  } else if (changed === 0) {
    el.innerHTML = 'In step with <code>data/peak-status.json</code>.';
  } else {
    el.innerHTML = `<strong>${changed} change${changed === 1 ? '' : 's'} in ${PeakStore.describe()} only.</strong>
       ${PeakStore.account().available
         ? 'Sign in below to keep them in your account, or export'
         : 'Export'} and commit the file as <code>data/peak-status.json</code>.`;
  }
}

// ─── Account ──────────────────────────────────────────────────────────────────

/** Sign-in by magic link. Absent entirely when config.js has no Supabase. */
function renderAccount() {
  const el = document.getElementById('peaks-account');
  if (!el) return;

  const { available, email } = PeakStore.account();
  if (!available) {
    el.hidden = true;
    return;
  }

  if (email) {
    el.innerHTML = `
      <span class="peaks-account-who">Signed in as <strong>${escapeHtml(email)}</strong></span>
      <button type="button" id="peaks-sign-out">Sign out</button>
    `;
    el.querySelector('#peaks-sign-out').addEventListener('click', async () => {
      try {
        await PeakStore.signOut();
      } catch (err) {
        console.error('[peaks] sign-out failed:', err);
        flash('Could not sign out', true);
      }
    });
    return;
  }

  el.innerHTML = `
    <form id="peaks-sign-in" class="peaks-sign-in">
      <label class="peaks-field">
        <span>Sync across devices</span>
        <input type="email" name="email" placeholder="you@example.com" autocomplete="email" required>
      </label>
      <button type="submit">Email me a sign-in link</button>
    </form>
  `;
  const form = el.querySelector('#peaks-sign-in');
  form.addEventListener('submit', async event => {
    event.preventDefault();
    const email = form.email.value.trim();
    const button = form.querySelector('button');
    button.disabled = true;
    try {
      await PeakStore.signIn(email);
      el.innerHTML = `<p class="peaks-note">Check <strong>${escapeHtml(email)}</strong> for a sign-in link.
        Open it on this device and your list moves to your account.</p>`;
    } catch (err) {
      console.error('[peaks] sign-in failed:', err);
      flash(err?.message ?? 'Could not send the link', true);
      button.disabled = false;
    }
  });
}

function renderTaggedList() {
  const el = document.getElementById('peaks-tagged');
  if (!el) return;

  const entries = taggedEntries();
  if (!entries.length) {
    el.innerHTML = '<p class="peaks-empty">Nothing tagged yet — click a peak on the map.</p>';
    renderCounts();
    renderStats();
    renderSaveState();
    return;
  }

  el.innerHTML = entries.map(({ id, entry, feature }) => `
    <button type="button" class="peaks-tagged-row" data-id="${id}" ${feature ? '' : 'disabled'}>
      <span class="peaks-swatch" style="background:${STATUSES[entry.status]?.color ?? '#888'}"></span>
      <span class="peaks-tagged-name">${escapeHtml(entry.name ?? feature?.properties.name ?? id)}</span>
      <span class="peaks-tagged-ele">${entry.ele ?? feature?.properties.ele ?? '?'} m</span>
    </button>
  `).join('');

  el.querySelectorAll('.peaks-tagged-row').forEach(row => {
    row.addEventListener('click', () => {
      const feature = state.byId.get(row.dataset.id);
      if (!feature) return;
      state.map.flyTo({ center: feature.geometry.coordinates, zoom: 13.5 });
      openPicker(feature);
    });
  });

  renderCounts();
  renderStats();
  renderSaveState();
  renderTrackBar();

  // Both need an account, so they appear only with one.
  const addButton = document.getElementById('peaks-add-route');
  if (addButton) {
    addButton.hidden = !RouteStore.available();
    if (!addButton.dataset.wired) {
      addButton.dataset.wired = 'yes';
      addButton.addEventListener('click', () => RouteForm.open());
    }
  }

  const importButton = document.getElementById('peaks-import-hikes');
  if (importButton) {
    importButton.hidden = !RouteStore.available();
    if (!importButton.dataset.wired) {
      importButton.dataset.wired = 'yes';
      importButton.addEventListener('click', () => importRepoHikes(importButton));
    }
  }
}

// ─── Export / import ──────────────────────────────────────────────────────────

function exportStatuses() {
  const payload = PeakStore.toExport();

  const blob = new Blob([JSON.stringify(payload, null, 2) + '\n'], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = 'peak-status.json';
  link.click();
  URL.revokeObjectURL(url);

  flash(`Exported ${Object.keys(payload.peaks).length} peaks`);
}

async function importStatuses(event) {
  const file = event.target.files?.[0];
  if (!file) return;

  try {
    const applied = await PeakStore.importAll(
      JSON.parse(await file.text()),
      status => status in STATUSES
    );

    for (const id of applied) {
      const feature = state.byId.get(id);
      if (feature) feature.properties.status = PeakStore.get(id).status;
    }

    refreshSource();
    applyFilters();
    renderTaggedList();
    flash(`Imported ${applied.length} peaks`);
  } catch (err) {
    console.error('[peaks] import failed:', err);
    flash('That file is not a peak-status export', true);
  } finally {
    event.target.value = '';
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Called by app.js when the Peaks tab is shown again. While a tab is hidden its
 * container has no dimensions, so MapLibre's cached size is stale and the map
 * comes back distorted until something forces a recalculation.
 */
function resizePeaksMap() {
  state.map?.resize();
}

let flashTimer = null;

function flash(message, isError = false) {
  let el = document.getElementById('peaks-flash');
  if (!el) {
    el = document.createElement('div');
    el.id = 'peaks-flash';
    document.body.appendChild(el);
  }
  el.textContent = message;
  el.className = `peaks-flash is-visible${isError ? ' is-error' : ''}`;
  clearTimeout(flashTimer);
  flashTimer = setTimeout(() => { el.className = 'peaks-flash'; }, 2600);
}

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, c =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])
  );
}
