/**
 * Peaks tab — browse every peak in the region and tag it dream / planned /
 * attempted / done.
 *
 * Peaks come from data/peaks.geojson, a snapshot of OpenStreetMap generated by
 * scripts/fetch-peaks.mjs. Statuses come from PeakStore (store.js), which hides
 * whether they live in this browser or in a database behind one interface.
 */

const PEAKS_URL = 'data/peaks.geojson';

const PEAK_STYLE = `https://api.maptiler.com/maps/01977a3c-1420-7d86-8992-edcec1cbca8d/style.json?key=${CONFIG?.MAPTILER_API_KEY}`;

/** Order matters — it drives the legend, the filter list and the picker. */
const STATUSES = {
  done:      { label: 'Done',      color: '#2f7d32', hint: 'Summited' },
  planned:   { label: 'Planned',   color: '#f0a500', hint: 'Actually going' },
  dream:     { label: 'Dream',     color: '#7b5ea7', hint: 'Someday' },
  attempted: { label: 'Attempted', color: '#d1495b', hint: 'Tried, turned back' },
  none:      { label: 'Untagged',  color: '#8d9296', hint: 'Not on the list' }
};
const TAGGED = Object.keys(STATUSES).filter(s => s !== 'none');

const COUNTRY_NAMES = { DE: 'Germany', AT: 'Austria', IT: 'Italy', CH: 'Switzerland', '??': 'Unknown' };

const state = {
  features: [],              // GeoJSON features, properties.status kept current
  byId: new Map(),           // peak id (string) → feature, to avoid rescanning
  statuses: new Map(),       // peak id (string) → { status, date, note, … }, owned by PeakStore
  map: null,
  popup: null,
  hoverPopup: null,
  filters: {
    minEle: 1000,
    maxEle: 3000,
    statuses: new Set([...TAGGED, 'none']),
    countries: new Set(),    // empty = all
    search: '',
    // Shifts the whole zoom ladder: negative shows more, positive shows less.
    detail: 0
  }
};

/**
 * An untagged peak is drawn once the map reaches the zoom its isolation earned
 * it, so a secondary summit like Kleinglockner (70 m from Großglockner) stays
 * hidden until you are close enough for it to mean something.
 *
 * Tagged peaks have no zoom tier. They are drawn at every zoom and compete for
 * space instead: where two would overlap, the one earlier in this list keeps
 * its place, so a done peak is never pushed out by a planned one. Lower
 * statuses fill whatever room is left, and filtering a status out frees its
 * room for the rest.
 */
const STATUS_PRIORITY = ['done', 'planned', 'dream', 'attempted'];

/**
 * The peak's own zoom tier, defaulting to "always visible" when the property is
 * absent — an older snapshot should degrade to showing everything, never to a
 * blank map.
 */
const PEAK_MIN_ZOOM = ['coalesce', ['get', 'minZoom'], 0];

// ─── Load ─────────────────────────────────────────────────────────────────────

async function initPeaks() {
  const root = document.getElementById('tab-peaks');

  let peaks;
  try {
    peaks = await fetch(PEAKS_URL).then(r => {
      if (!r.ok) throw new Error(`${PEAKS_URL} → HTTP ${r.status}`);
      return r.json();
    });
  } catch (err) {
    console.error('[peaks]', err);
    root.querySelector('#peaks-map').innerHTML =
      `<p class="peaks-error">Could not load ${PEAKS_URL}. Run <code>node scripts/fetch-peaks.mjs</code> to generate it.</p>`;
    return;
  }

  state.statuses = await PeakStore.open();

  state.features = peaks.features.map(f => ({
    ...f,
    properties: {
      ...f.properties,
      country: f.properties.country ?? '??',
      status: state.statuses.get(String(f.properties.id))?.status ?? 'none'
    }
  }));

  state.byId = new Map(state.features.map(f => [String(f.properties.id), f]));

  const elevations = state.features.map(f => f.properties.ele);
  state.filters.minEle = Math.floor(Math.min(...elevations) / 100) * 100;
  state.filters.maxEle = Math.ceil(Math.max(...elevations) / 100) * 100;

  console.log(`[peaks] ${state.features.length} peaks, ${state.statuses.size} tagged`);

  buildPanel(peaks);
  buildMap();

  // Signing in or out swaps the whole list for the other backend's.
  PeakStore.onChange(statuses => {
    state.statuses = statuses;
    for (const feature of state.features) {
      feature.properties.status = statuses.get(String(feature.properties.id))?.status ?? 'none';
    }
    refreshSource();
    applyFilters();
    renderTaggedList();
    renderAccount();
  });
}

// ─── Map ──────────────────────────────────────────────────────────────────────

const collection = () => ({ type: 'FeatureCollection', features: state.features });

function buildMap() {
  const map = new maplibregl.Map({
    container: 'peaks-map',
    style: PEAK_STYLE,
    center: [11.6, 47.55],
    zoom: 9,
    // v3 only takes a boolean here, so the credit goes on the control itself.
    attributionControl: false
  });
  state.map = map;

  map.addControl(new maplibregl.AttributionControl({
    compact: true,
    customAttribution: 'Peak data © OpenStreetMap contributors (ODbL)'
  }), 'bottom-right');
  map.addControl(new maplibregl.NavigationControl(), 'top-right');
  // Bottom-left belongs to the floating panel now.
  map.addControl(new maplibregl.ScaleControl({ maxWidth: 120 }), 'bottom-right');

  map.on('error', e => console.error('[peaks] map error:', e?.error?.message ?? e));

  map.on('load', () => {
    // The basemap labels its own peaks; ours carry the status, so drop theirs
    // rather than stacking two labels on one summit.
    for (const id of ['Peak labels', 'Peak labels (US)']) {
      if (map.getLayer(id)) map.setLayoutProperty(id, 'visibility', 'none');
    }

    map.addSource('peaks', { type: 'geojson', data: collection(), promoteId: 'id' });

    addStatusIcons(map);

    // A peak that dominates its surroundings should look like it. `rank` runs
    // from 0 for a minor secondary summit to 1 for something like Großglockner.
    const rank = ['interpolate', ['linear'], PEAK_MIN_ZOOM,
      6, 1,
      10, 0.55,
      14, 0
    ];

    // Untagged peaks: plain dots, which never collide, gated by zoom tier.
    map.addLayer({
      id: 'peaks-dots',
      type: 'circle',
      source: 'peaks',
      paint: {
        'circle-color': STATUSES.none.color,
        'circle-radius': ['interpolate', ['linear'], ['zoom'],
          7,  ['+', 1.5, ['*', rank, 3.5]],
          10, ['+', 2.5, ['*', rank, 4.5]],
          14, ['+', 4.5, ['*', rank, 6]]
        ],
        'circle-stroke-color': '#ffffff',
        'circle-stroke-width': 1,
        'circle-opacity': 0.85
      }
    });

    map.addLayer({
      id: 'peaks-labels',
      type: 'symbol',
      source: 'peaks',
      layout: {
        ...labelLayout(rank),
        // When two labels collide the more dominant peak keeps its name.
        'symbol-sort-key': PEAK_MIN_ZOOM
      },
      paint: LABEL_PAINT
    });

    // Tagged peaks: icons rather than circles, because only symbols take part
    // in collision. Added last, so they are placed before every other label
    // on the map and nothing untagged can crowd them out.
    const statusRank = ['match', ['get', 'status'],
      ...STATUS_PRIORITY.flatMap((key, i) => [key, i]),
      STATUS_PRIORITY.length
    ];
    map.addLayer({
      id: 'peaks-tagged',
      type: 'symbol',
      source: 'peaks',
      layout: {
        ...labelLayout(rank),
        'icon-image': ['concat', 'status-', ['get', 'status']],
        // Same sizes the tagged circles had; the icon's inner radius is 10 px.
        'icon-size': ['interpolate', ['linear'], ['zoom'],
          7,  ['/', ['+', 3, ['*', rank, 3.5]], 10],
          10, ['/', ['+', 4.5, ['*', rank, 4.5]], 10],
          14, ['/', ['+', 7.5, ['*', rank, 6]], 10]
        ],
        'icon-padding': 1,
        // Placed in ascending order: status first, dominance within a status.
        'symbol-sort-key': ['+', ['*', statusRank, 100], PEAK_MIN_ZOOM]
      },
      paint: LABEL_PAINT
    });

    applyFilters();

    // The count of what is on screen changes with zoom, not just with filters.
    map.on('zoomend', renderCounts);
    map.on('moveend', renderCounts);

    for (const layer of ['peaks-dots', 'peaks-tagged']) {
      map.on('click', layer, e => openPicker(e.features[0]));
      map.on('mouseenter', layer, e => {
        map.getCanvas().style.cursor = 'pointer';
        showHover(e.features[0]);
      });
      map.on('mouseleave', layer, () => {
        map.getCanvas().style.cursor = '';
        state.hoverPopup?.remove();
        state.hoverPopup = null;
      });
    }
  });
}

const LABEL_PAINT = {
  'text-color': '#33302c',
  'text-halo-color': '#ffffff',
  'text-halo-width': 1.4
};

function labelLayout(rank) {
  return {
    'text-field': ['concat', ['get', 'name'], '  ', ['to-string', ['get', 'ele']], ' m'],
    'text-font': ['Noto Sans Regular'],
    // Dominant peaks get a larger label as well as an earlier one.
    'text-size': ['interpolate', ['linear'], ['zoom'],
      9,  ['+', 9.5, ['*', rank, 3]],
      14, ['+', 11.5, ['*', rank, 3.5]]
    ],
    'text-offset': [0, 1.1],
    'text-anchor': 'top',
    // A crowded label drops before its dot does.
    'text-optional': true
  };
}

/**
 * One dot per status, drawn on a canvas at 2x so it stays crisp: a 10 px disc
 * in the status colour inside a 2 px white ring, the look the circles had.
 */
function addStatusIcons(map) {
  const radius = 20, ring = 4, size = 2 * (radius + ring);
  for (const key of TAGGED) {
    const canvas = document.createElement('canvas');
    canvas.width = canvas.height = size;
    const ctx = canvas.getContext('2d');
    for (const [r, color] of [[radius + ring, '#ffffff'], [radius, STATUSES[key].color]]) {
      ctx.beginPath();
      ctx.arc(size / 2, size / 2, r, 0, 2 * Math.PI);
      ctx.fillStyle = color;
      ctx.fill();
    }
    map.addImage(`status-${key}`, ctx.getImageData(0, 0, size, size), { pixelRatio: 2 });
  }
}

function refreshSource() {
  state.map?.getSource('peaks')?.setData(collection());
}

function applyFilters() {
  if (!state.map?.getLayer('peaks-dots')) return;
  const { minEle, maxEle, statuses, countries, search } = state.filters;

  const filter = ['all',
    ['>=', ['get', 'ele'], minEle],
    ['<=', ['get', 'ele'], maxEle],
    ['in', ['get', 'status'], ['literal', [...statuses]]]
  ];
  // country is "AT", "DE" or "AT/DE" for a border summit — a substring test
  // matches the border case under either country.
  if (countries.size) {
    filter.push(['any', ...[...countries].map(c => ['in', c, ['get', 'country']])]);
  }
  if (search.trim()) {
    filter.push(['in', search.trim().toLowerCase(), ['downcase', ['coalesce', ['get', 'name'], '']]]);
  }

  const untagged = [...filter, ['==', ['get', 'status'], 'none'], zoomRankFilter()];
  state.map.setFilter('peaks-dots', untagged);
  state.map.setFilter('peaks-labels', untagged);
  state.map.setFilter('peaks-tagged', [...filter, ['!=', ['get', 'status'], 'none']]);
  renderCounts();
}

/**
 * Show an untagged peak once the map reaches its `minZoom`, shifted by the
 * detail slider. MapLibre does allow `zoom` inside a filter; it is evaluated
 * at integer zoom levels, which is all this needs. PEAK_MIN_ZOOM defaults to 0,
 * so a snapshot generated before minZoom existed shows everything rather than
 * failing on null and hiding every peak.
 */
function zoomRankFilter() {
  return ['<=', ['-', PEAK_MIN_ZOOM, state.filters.detail], ['zoom']];
}

/**
 * Mirrors the layer filters for the panel counters. Tagged peaks pass at any
 * zoom; whether one actually fits on screen is up to collision, which the
 * counter cannot see.
 */
function passesZoomRank(properties, zoom) {
  if (properties.status !== 'none') return true;
  return (properties.minZoom ?? 0) - state.filters.detail <= zoom;
}

function visibleFeatures() {
  const { minEle, maxEle, statuses, countries, search } = state.filters;
  const needle = search.trim().toLowerCase();
  const zoom = Math.floor(state.map?.getZoom() ?? 9);
  return state.features.filter(f => {
    const p = f.properties;
    if (p.ele < minEle || p.ele > maxEle) return false;
    if (!statuses.has(p.status)) return false;
    if (countries.size && ![...countries].some(c => p.country.includes(c))) return false;
    if (needle && !(p.name ?? '').toLowerCase().includes(needle)) return false;
    if (!passesZoomRank(p, zoom)) return false;
    return true;
  });
}

// ─── Status editing ───────────────────────────────────────────────────────────

async function setStatus(id, status) {
  const key = String(id);
  const feature = state.byId.get(key);
  if (!feature) return;

  const entry = status === 'none'
    // Keep a tombstone: the committed baseline would otherwise put it back.
    ? { status: 'none', name: feature.properties.name, ele: feature.properties.ele }
    : {
        ...(PeakStore.get(key) ?? {}),
        status,
        name: feature.properties.name,
        ele: feature.properties.ele,
        country: feature.properties.country === '??' ? null : feature.properties.country,
        updated: new Date().toISOString().slice(0, 10)
      };

  if (!(await PeakStore.set(key, entry))) {
    flash(`Could not save ${feature.properties.name} — try again`, true);
    return;
  }

  feature.properties.status = status;
  refreshSource();
  applyFilters();
  renderTaggedList();
}

/** Everything actually tagged — tombstones and untagged peaks excluded. */
function taggedEntries() {
  const entries = [];
  for (const [id, entry] of state.statuses) {
    if (!entry || entry.status === 'none') continue;
    const feature = state.byId.get(id);
    entries.push({ id, entry, feature });
  }
  return entries.sort((a, b) =>
    TAGGED.indexOf(a.entry.status) - TAGGED.indexOf(b.entry.status) ||
    (b.feature?.properties.ele ?? 0) - (a.feature?.properties.ele ?? 0)
  );
}

// ─── Popups ───────────────────────────────────────────────────────────────────

function showHover(feature) {
  const p = feature.properties;
  state.hoverPopup?.remove();
  state.hoverPopup = new maplibregl.Popup({ closeButton: false, closeOnClick: false, offset: 10, className: 'peak-hover' })
    .setLngLat(feature.geometry.coordinates)
    .setHTML(`<strong>${escapeHtml(p.name)}</strong> · ${p.ele} m`)
    .addTo(state.map);
}

function openPicker(feature) {
  const p = feature.properties;
  const id = String(p.id);
  const current = state.statuses.get(id)?.status ?? 'none';

  const el = document.createElement('div');
  el.className = 'peak-picker';
  el.innerHTML = `
    <h3>${escapeHtml(p.name)}</h3>
    <p class="peak-picker-meta">
      ${p.ele} m${p.prominence ? ` · ${p.prominence} m prominence` : ''}
      ${p.country && p.country !== '??' ? ` · ${p.country.split('/').map(c => COUNTRY_NAMES[c] ?? c).join(' / ')}` : ''}
    </p>
    <p class="peak-picker-meta">${describeIsolation(p.isolation)}</p>
    <div class="peak-picker-options"></div>
    <div class="peak-picker-links">
      <a href="https://www.openstreetmap.org/node/${p.id}" target="_blank" rel="noopener">OSM</a>
      ${p.wikipedia ? `<a href="https://${wikipediaHost(p.wikipedia)}" target="_blank" rel="noopener">Wikipedia</a>` : ''}
      <a href="https://www.google.com/maps/dir/?api=1&destination=${feature.geometry.coordinates[1]},${feature.geometry.coordinates[0]}" target="_blank" rel="noopener">Directions</a>
    </div>
  `;

  const options = el.querySelector('.peak-picker-options');
  for (const key of [...TAGGED, 'none']) {
    const { label, color, hint } = STATUSES[key];
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = `peak-option${key === current ? ' is-current' : ''}`;
    btn.style.setProperty('--option-color', color);
    btn.title = hint;
    btn.textContent = label;
    btn.addEventListener('click', async () => {
      await setStatus(id, key);
      state.popup?.remove();
      flash(key === 'none' ? `${p.name} cleared` : `${p.name} → ${label}`);
    });
    options.appendChild(btn);
  }

  state.popup?.remove();
  state.popup = new maplibregl.Popup({ offset: 14, maxWidth: '320px', className: 'peak-popup' })
    .setLngLat(feature.geometry.coordinates)
    .setDOMContent(el)
    .addTo(state.map);
}

/**
 * Says in words what the isolation figure means, since it is the thing deciding
 * whether a peak is treated as a mountain or as part of its bigger neighbour.
 */
function describeIsolation(metres) {
  if (metres === null || metres === undefined) return 'Highest peak in the dataset';
  if (metres < 500) return `A secondary summit — higher ground only ${Math.round(metres)} m away`;
  if (metres < 2000) return `${(metres / 1000).toFixed(1)} km to higher ground`;
  return `${Math.round(metres / 1000)} km to higher ground — a dominant peak`;
}

const wikipediaHost = tag => {
  const [lang, ...rest] = String(tag).split(':');
  return rest.length
    ? `${lang}.wikipedia.org/wiki/${encodeURIComponent(rest.join(':'))}`
    : `en.wikipedia.org/wiki/${encodeURIComponent(tag)}`;
};

// ─── Panel ────────────────────────────────────────────────────────────────────

function buildPanel(peaks) {
  const countries = [...new Set(
    state.features.flatMap(f => f.properties.country.split('/'))
  )].sort();

  const { minEle, maxEle } = state.filters;

  document.getElementById('peaks-panel').innerHTML = `
    <header class="peaks-panel-head">
      <h2>Peak Planner</h2>
      <p>Click any peak to mark it.</p>
    </header>

    <div id="peaks-counts" class="peaks-counts"></div>

    <section class="peaks-filters">
      <h3>Filters</h3>

      <label class="peaks-field">
        <span>Search</span>
        <input type="search" id="peaks-search" placeholder="Peak name…" autocomplete="off">
      </label>

      <label class="peaks-field">
        <span>Detail — <output id="peaks-detail-out">balanced</output></span>
        <input type="range" id="peaks-detail" min="-2" max="3" step="1" value="0">
        <small class="peaks-hint">Secondary summits stay hidden until you zoom in. Slide right to reveal them sooner.</small>
      </label>

      <label class="peaks-field">
        <span>Minimum elevation — <output id="peaks-min-out">${minEle} m</output></span>
        <input type="range" id="peaks-min" min="${minEle}" max="${maxEle}" step="50" value="${minEle}">
      </label>

      <label class="peaks-field">
        <span>Maximum elevation — <output id="peaks-max-out">${maxEle} m</output></span>
        <input type="range" id="peaks-max" min="${minEle}" max="${maxEle}" step="50" value="${maxEle}">
      </label>

      <fieldset class="peaks-field">
        <legend>Status</legend>
        <div class="peaks-checks" id="peaks-status-filters">
          ${[...TAGGED, 'none'].map(key => `
            <label class="peaks-check">
              <input type="checkbox" value="${key}" checked>
              <span class="peaks-swatch" style="background:${STATUSES[key].color}"></span>
              ${STATUSES[key].label}
            </label>
          `).join('')}
        </div>
      </fieldset>

      <fieldset class="peaks-field">
        <legend>Country</legend>
        <div class="peaks-checks" id="peaks-country-filters">
          ${countries.map(code => `
            <label class="peaks-check">
              <input type="checkbox" value="${code}">
              ${COUNTRY_NAMES[code] ?? code}
            </label>
          `).join('')}
        </div>
      </fieldset>
    </section>

    <section class="peaks-actions">
      <h3>Your list</h3>
      <div id="peaks-tagged" class="peaks-tagged"></div>
      <div class="peaks-buttons">
        <button type="button" id="peaks-export">Export JSON</button>
        <label class="peaks-import">
          Import
          <input type="file" id="peaks-import" accept="application/json,.json" hidden>
        </label>
      </div>
      <p id="peaks-save-state" class="peaks-note"></p>
      <div id="peaks-account" class="peaks-account"></div>
      <p class="peaks-note peaks-source">
        ${state.features.length} peaks · snapshot ${peaks.generated ?? '—'} ·
        ${peaks.attribution ?? '© OpenStreetMap contributors'}
      </p>
    </section>
  `;

  wirePanel();
  renderTaggedList();
  renderAccount();
}

function wirePanel() {
  const search = document.getElementById('peaks-search');
  search.addEventListener('input', () => {
    state.filters.search = search.value;
    applyFilters();
  });

  const min = document.getElementById('peaks-min');
  const max = document.getElementById('peaks-max');
  const minOut = document.getElementById('peaks-min-out');
  const maxOut = document.getElementById('peaks-max-out');

  min.addEventListener('input', () => {
    if (Number(min.value) > Number(max.value)) max.value = min.value;
    state.filters.minEle = Number(min.value);
    state.filters.maxEle = Number(max.value);
    minOut.textContent = `${min.value} m`;
    maxOut.textContent = `${max.value} m`;
    applyFilters();
  });

  max.addEventListener('input', () => {
    if (Number(max.value) < Number(min.value)) min.value = max.value;
    state.filters.minEle = Number(min.value);
    state.filters.maxEle = Number(max.value);
    minOut.textContent = `${min.value} m`;
    maxOut.textContent = `${max.value} m`;
    applyFilters();
  });

  document.getElementById('peaks-status-filters').addEventListener('change', e => {
    const box = e.target;
    state.filters.statuses[box.checked ? 'add' : 'delete'](box.value);
    applyFilters();
  });

  document.getElementById('peaks-country-filters').addEventListener('change', e => {
    const box = e.target;
    state.filters.countries[box.checked ? 'add' : 'delete'](box.value);
    applyFilters();
  });

  const detail = document.getElementById('peaks-detail');
  const detailOut = document.getElementById('peaks-detail-out');
  const DETAIL_LABELS = { '-2': 'major peaks only', '-1': 'sparse', 0: 'balanced', 1: 'more', 2: 'dense', 3: 'everything' };
  detail.addEventListener('input', () => {
    state.filters.detail = Number(detail.value);
    detailOut.textContent = DETAIL_LABELS[detail.value] ?? detail.value;
    applyFilters();
  });

  document.getElementById('peaks-export').addEventListener('click', exportStatuses);
  document.getElementById('peaks-import').addEventListener('change', importStatuses);

  const toggle = document.getElementById('peaks-panel-toggle');
  toggle.addEventListener('click', () => {
    const collapsed = document.body.classList.toggle('peaks-panel-collapsed');
    toggle.setAttribute('aria-expanded', String(!collapsed));
    toggle.title = collapsed ? 'Show the panel' : 'Hide the panel';
    toggle.firstElementChild.textContent = collapsed ? '›' : '‹';
    // The map keeps its full size underneath; only the overlay moves, so there
    // is nothing to resize — but the centre of what you can see has shifted.
    state.map?.easeTo({ duration: 200 });
  });
}

function renderCounts() {
  const el = document.getElementById('peaks-counts');
  if (!el) return;

  const visible = visibleFeatures();
  const counts = Object.fromEntries(TAGGED.map(s => [s, 0]));
  for (const { entry } of taggedEntries()) counts[entry.status]++;

  el.innerHTML = `
    <div class="peaks-count peaks-count--total">
      <span class="peaks-count-value">${visible.length}</span>
      <span class="peaks-count-label">peaks shown</span>
    </div>
    ${TAGGED.map(key => `
      <div class="peaks-count">
        <span class="peaks-count-value" style="color:${STATUSES[key].color}">${counts[key]}</span>
        <span class="peaks-count-label">${STATUSES[key].label}</span>
      </div>
    `).join('')}
  `;
}

/**
 * Says where tagging a peak actually writes. Signed in, that is the account.
 * Signed out it is localStorage, which nobody else sees until the file is
 * exported and committed, so the least this can do is not pretend it is saved.
 */
function renderSaveState() {
  const el = document.getElementById('peaks-save-state');
  if (!el) return;

  const changed = PeakStore.pendingCount();
  el.classList.toggle('is-unsaved', changed > 0 && !PeakStore.isShared());

  if (PeakStore.isShared()) {
    el.innerHTML = `Saved to your account — ${PeakStore.describe()}.`;
  } else if (changed === 0) {
    el.innerHTML = 'In step with <code>data/peak-status.json</code>.';
  } else {
    el.innerHTML = `<strong>${changed} change${changed === 1 ? '' : 's'} in ${PeakStore.describe()} only.</strong>
       ${PeakStore.account().available
         ? 'Sign in below to keep them in your account, or export'
         : 'Export'} and commit the file as <code>data/peak-status.json</code>.`;
  }
}

// ─── Account ──────────────────────────────────────────────────────────────────

/** Sign-in by magic link. Absent entirely when config.js has no Supabase. */
function renderAccount() {
  const el = document.getElementById('peaks-account');
  if (!el) return;

  const { available, email } = PeakStore.account();
  if (!available) {
    el.hidden = true;
    return;
  }

  if (email) {
    el.innerHTML = `
      <span class="peaks-account-who">Signed in as <strong>${escapeHtml(email)}</strong></span>
      <button type="button" id="peaks-sign-out">Sign out</button>
    `;
    el.querySelector('#peaks-sign-out').addEventListener('click', async () => {
      try {
        await PeakStore.signOut();
      } catch (err) {
        console.error('[peaks] sign-out failed:', err);
        flash('Could not sign out', true);
      }
    });
    return;
  }

  el.innerHTML = `
    <form id="peaks-sign-in" class="peaks-sign-in">
      <label class="peaks-field">
        <span>Sync across devices</span>
        <input type="email" name="email" placeholder="you@example.com" autocomplete="email" required>
      </label>
      <button type="submit">Email me a sign-in link</button>
    </form>
  `;
  const form = el.querySelector('#peaks-sign-in');
  form.addEventListener('submit', async event => {
    event.preventDefault();
    const email = form.email.value.trim();
    const button = form.querySelector('button');
    button.disabled = true;
    try {
      await PeakStore.signIn(email);
      el.innerHTML = `<p class="peaks-note">Check <strong>${escapeHtml(email)}</strong> for a sign-in link.
        Open it on this device and your list moves to your account.</p>`;
    } catch (err) {
      console.error('[peaks] sign-in failed:', err);
      flash(err?.message ?? 'Could not send the link', true);
      button.disabled = false;
    }
  });
}

function renderTaggedList() {
  const el = document.getElementById('peaks-tagged');
  if (!el) return;

  const entries = taggedEntries();
  if (!entries.length) {
    el.innerHTML = '<p class="peaks-empty">Nothing tagged yet — click a peak on the map.</p>';
    renderCounts();
    renderSaveState();
    return;
  }

  el.innerHTML = entries.map(({ id, entry, feature }) => `
    <button type="button" class="peaks-tagged-row" data-id="${id}" ${feature ? '' : 'disabled'}>
      <span class="peaks-swatch" style="background:${STATUSES[entry.status]?.color ?? '#888'}"></span>
      <span class="peaks-tagged-name">${escapeHtml(entry.name ?? feature?.properties.name ?? id)}</span>
      <span class="peaks-tagged-ele">${entry.ele ?? feature?.properties.ele ?? '?'} m</span>
    </button>
  `).join('');

  el.querySelectorAll('.peaks-tagged-row').forEach(row => {
    row.addEventListener('click', () => {
      const feature = state.byId.get(row.dataset.id);
      if (!feature) return;
      state.map.flyTo({ center: feature.geometry.coordinates, zoom: 13.5 });
      openPicker(feature);
    });
  });

  renderCounts();
  renderSaveState();
}

// ─── Export / import ──────────────────────────────────────────────────────────

function exportStatuses() {
  const payload = PeakStore.toExport();

  const blob = new Blob([JSON.stringify(payload, null, 2) + '\n'], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = 'peak-status.json';
  link.click();
  URL.revokeObjectURL(url);

  flash(`Exported ${Object.keys(payload.peaks).length} peaks`);
}

async function importStatuses(event) {
  const file = event.target.files?.[0];
  if (!file) return;

  try {
    const applied = await PeakStore.importAll(
      JSON.parse(await file.text()),
      status => status in STATUSES
    );

    for (const id of applied) {
      const feature = state.byId.get(id);
      if (feature) feature.properties.status = PeakStore.get(id).status;
    }

    refreshSource();
    applyFilters();
    renderTaggedList();
    flash(`Imported ${applied.length} peaks`);
  } catch (err) {
    console.error('[peaks] import failed:', err);
    flash('That file is not a peak-status export', true);
  } finally {
    event.target.value = '';
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Called by app.js when the Peaks tab is shown again. While a tab is hidden its
 * container has no dimensions, so MapLibre's cached size is stale and the map
 * comes back distorted until something forces a recalculation.
 */
function resizePeaksMap() {
  state.map?.resize();
}

let flashTimer = null;

function flash(message, isError = false) {
  let el = document.getElementById('peaks-flash');
  if (!el) {
    el = document.createElement('div');
    el.id = 'peaks-flash';
    document.body.appendChild(el);
  }
  el.textContent = message;
  el.className = `peaks-flash is-visible${isError ? ' is-error' : ''}`;
  clearTimeout(flashTimer);
  flashTimer = setTimeout(() => { el.className = 'peaks-flash'; }, 2600);
}

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, c =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])
  );
}
