/**
 * Peaks tab — browse every peak in the region and tag it dream / planned /
 * attempted / done.
 *
 * Peaks come from data/peaks.geojson, a snapshot of OpenStreetMap generated by
 * scripts/fetch-peaks.mjs. Statuses are the merge of two layers:
 *
 *   data/peak-status.json   committed baseline, shared across devices via git
 *   localStorage            edits made in this browser, which win
 *
 * "Export" writes the merged result back out as peak-status.json so it can be
 * committed and become the new baseline. Accounts and a real database are #3.
 */

const PEAKS_URL = 'data/peaks.geojson';
const PEAK_STATUS_URL = 'data/peak-status.json';
const STORAGE_KEY = 'mmj.peak-status.v1';

const PEAK_STYLE = `https://api.maptiler.com/maps/01977a3c-1420-7d86-8992-edcec1cbca8d/style.json?key=${CONFIG?.MAPTILER_API_KEY}`;

/** Order matters — it drives the legend, the filter list and the picker. */
const STATUSES = {
  done:      { label: 'Done',      color: '#2f7d32', hint: 'Summited' },
  planned:   { label: 'Planned',   color: '#f0a500', hint: 'Actually going' },
  dream:     { label: 'Dream',     color: '#7b5ea7', hint: 'Someday' },
  attempted: { label: 'Attempted', color: '#d1495b', hint: 'Tried, turned back' },
  none:      { label: 'Untagged',  color: '#8d9296', hint: 'Not on the list' }
};
const TAGGED = Object.keys(STATUSES).filter(s => s !== 'none');

const COUNTRY_NAMES = { DE: 'Germany', AT: 'Austria', IT: 'Italy', CH: 'Switzerland', '??': 'Unknown' };

const state = {
  features: [],              // GeoJSON features, properties.status kept current
  statuses: new Map(),       // peak id (string) → { status, date, note, … }
  baseline: {},              // what data/peak-status.json said
  map: null,
  popup: null,
  hoverPopup: null,
  filters: {
    minEle: 1000,
    maxEle: 3000,
    statuses: new Set([...TAGGED, 'none']),
    countries: new Set(),    // empty = all
    search: ''
  }
};

// ─── Local storage ────────────────────────────────────────────────────────────

function loadLocalEdits() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : {};
  } catch (err) {
    console.warn('[peaks] could not read local edits:', err);
    return {};
  }
}

function saveLocalEdits() {
  try {
    const edits = {};
    for (const [id, entry] of state.statuses) edits[id] = entry;
    localStorage.setItem(STORAGE_KEY, JSON.stringify(edits));
  } catch (err) {
    console.warn('[peaks] could not save local edits:', err);
    flash('Could not save locally — private browsing?', true);
  }
}

// ─── Load ─────────────────────────────────────────────────────────────────────

async function initPeaks() {
  const root = document.getElementById('tab-peaks');

  let peaks;
  try {
    peaks = await fetch(PEAKS_URL).then(r => {
      if (!r.ok) throw new Error(`${PEAKS_URL} → HTTP ${r.status}`);
      return r.json();
    });
  } catch (err) {
    console.error('[peaks]', err);
    root.querySelector('#peaks-map').innerHTML =
      `<p class="peaks-error">Could not load ${PEAKS_URL}. Run <code>node scripts/fetch-peaks.mjs</code> to generate it.</p>`;
    return;
  }

  // The committed baseline is optional — a fresh clone may not have one yet.
  const baseline = await fetch(PEAK_STATUS_URL)
    .then(r => (r.ok ? r.json() : { peaks: {} }))
    .catch(() => ({ peaks: {} }));

  state.baseline = baseline.peaks ?? {};
  const local = loadLocalEdits();
  for (const [id, entry] of Object.entries({ ...state.baseline, ...local })) {
    state.statuses.set(String(id), entry);
  }

  state.features = peaks.features.map(f => ({
    ...f,
    properties: {
      ...f.properties,
      country: f.properties.country ?? '??',
      status: state.statuses.get(String(f.properties.id))?.status ?? 'none'
    }
  }));

  const elevations = state.features.map(f => f.properties.ele);
  state.filters.minEle = Math.floor(Math.min(...elevations) / 100) * 100;
  state.filters.maxEle = Math.ceil(Math.max(...elevations) / 100) * 100;

  console.log(`[peaks] ${state.features.length} peaks, ${state.statuses.size} tagged`);

  buildPanel(peaks);
  buildMap();
}

// ─── Map ──────────────────────────────────────────────────────────────────────

const collection = () => ({ type: 'FeatureCollection', features: state.features });

function buildMap() {
  const map = new maplibregl.Map({
    container: 'peaks-map',
    style: PEAK_STYLE,
    center: [11.6, 47.55],
    zoom: 9,
    // v3 only takes a boolean here, so the credit goes on the control itself.
    attributionControl: false
  });
  state.map = map;

  map.addControl(new maplibregl.AttributionControl({
    compact: true,
    customAttribution: 'Peak data © OpenStreetMap contributors (ODbL)'
  }), 'bottom-right');
  map.addControl(new maplibregl.NavigationControl(), 'top-right');
  map.addControl(new maplibregl.ScaleControl({ maxWidth: 120 }), 'bottom-left');

  map.on('error', e => console.error('[peaks] map error:', e?.error?.message ?? e));

  map.on('load', () => {
    // The basemap labels its own peaks; ours carry the status, so drop theirs
    // rather than stacking two labels on one summit.
    for (const id of ['Peak labels', 'Peak labels (US)']) {
      if (map.getLayer(id)) map.setLayoutProperty(id, 'visibility', 'none');
    }

    map.addSource('peaks', { type: 'geojson', data: collection(), promoteId: 'id' });

    const isTagged = ['!=', ['get', 'status'], 'none'];
    const statusColor = ['match', ['get', 'status'],
      ...Object.entries(STATUSES).flatMap(([key, { color }]) => [key, color]),
      STATUSES.none.color
    ];

    map.addLayer({
      id: 'peaks-dots',
      type: 'circle',
      source: 'peaks',
      paint: {
        'circle-color': statusColor,
        'circle-radius': ['interpolate', ['linear'], ['zoom'],
          7,  ['case', isTagged, 4, 2],
          10, ['case', isTagged, 6, 3.5],
          14, ['case', isTagged, 11, 6]
        ],
        'circle-stroke-color': '#ffffff',
        'circle-stroke-width': ['case', isTagged, 2, 1],
        'circle-opacity': ['case', isTagged, 1, 0.85]
      }
    });

    map.addLayer({
      id: 'peaks-labels',
      type: 'symbol',
      source: 'peaks',
      layout: {
        'text-field': ['concat', ['get', 'name'], '  ', ['to-string', ['get', 'ele']], ' m'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 9, 10, 14, 13],
        'text-offset': [0, 1.1],
        'text-anchor': 'top',
        'text-optional': true,
        // Tagged peaks get placed first, then the highest summits.
        'symbol-sort-key': ['+', ['case', isTagged, 0, 10000], ['-', 4000, ['get', 'ele']]]
      },
      paint: {
        'text-color': '#33302c',
        'text-halo-color': '#ffffff',
        'text-halo-width': 1.4,
        // Untagged peaks would drown the map at low zoom, so fade them in.
        // `zoom` has to be the direct input to `interpolate`, hence the `case`
        // sitting in the output stops rather than wrapping the whole thing.
        'text-opacity': ['interpolate', ['linear'], ['zoom'],
          10.5, ['case', isTagged, 1, 0],
          11.5, 1
        ]
      }
    });

    applyFilters();

    map.on('click', 'peaks-dots', e => openPicker(e.features[0]));
    map.on('mouseenter', 'peaks-dots', e => {
      map.getCanvas().style.cursor = 'pointer';
      showHover(e.features[0]);
    });
    map.on('mouseleave', 'peaks-dots', () => {
      map.getCanvas().style.cursor = '';
      state.hoverPopup?.remove();
      state.hoverPopup = null;
    });
  });
}

function refreshSource() {
  state.map?.getSource('peaks')?.setData(collection());
}

function applyFilters() {
  if (!state.map?.getLayer('peaks-dots')) return;
  const { minEle, maxEle, statuses, countries, search } = state.filters;

  const filter = ['all',
    ['>=', ['get', 'ele'], minEle],
    ['<=', ['get', 'ele'], maxEle],
    ['in', ['get', 'status'], ['literal', [...statuses]]]
  ];
  // country is "AT", "DE" or "AT/DE" for a border summit — a substring test
  // matches the border case under either country.
  if (countries.size) {
    filter.push(['any', ...[...countries].map(c => ['in', c, ['get', 'country']])]);
  }
  if (search.trim()) {
    filter.push(['in', search.trim().toLowerCase(), ['downcase', ['coalesce', ['get', 'name'], '']]]);
  }

  for (const id of ['peaks-dots', 'peaks-labels']) state.map.setFilter(id, filter);
  renderCounts();
}

function visibleFeatures() {
  const { minEle, maxEle, statuses, countries, search } = state.filters;
  const needle = search.trim().toLowerCase();
  return state.features.filter(f => {
    const p = f.properties;
    if (p.ele < minEle || p.ele > maxEle) return false;
    if (!statuses.has(p.status)) return false;
    if (countries.size && ![...countries].some(c => p.country.includes(c))) return false;
    if (needle && !(p.name ?? '').toLowerCase().includes(needle)) return false;
    return true;
  });
}

// ─── Status editing ───────────────────────────────────────────────────────────

function setStatus(id, status) {
  const key = String(id);
  const feature = state.features.find(f => String(f.properties.id) === key);
  if (!feature) return;

  if (status === 'none') {
    // Keep a tombstone: the committed baseline would otherwise put it back.
    state.statuses.set(key, { status: 'none', name: feature.properties.name, ele: feature.properties.ele });
  } else {
    const previous = state.statuses.get(key) ?? {};
    state.statuses.set(key, {
      ...previous,
      status,
      name: feature.properties.name,
      ele: feature.properties.ele,
      country: feature.properties.country === '??' ? null : feature.properties.country,
      updated: new Date().toISOString().slice(0, 10)
    });
  }

  feature.properties.status = status;
  saveLocalEdits();
  refreshSource();
  applyFilters();
  renderTaggedList();
}

/** Everything actually tagged — tombstones and untagged peaks excluded. */
function taggedEntries() {
  const entries = [];
  for (const [id, entry] of state.statuses) {
    if (!entry || entry.status === 'none') continue;
    const feature = state.features.find(f => String(f.properties.id) === id);
    entries.push({ id, entry, feature });
  }
  return entries.sort((a, b) =>
    TAGGED.indexOf(a.entry.status) - TAGGED.indexOf(b.entry.status) ||
    (b.feature?.properties.ele ?? 0) - (a.feature?.properties.ele ?? 0)
  );
}

// ─── Popups ───────────────────────────────────────────────────────────────────

function showHover(feature) {
  const p = feature.properties;
  state.hoverPopup?.remove();
  state.hoverPopup = new maplibregl.Popup({ closeButton: false, closeOnClick: false, offset: 10, className: 'peak-hover' })
    .setLngLat(feature.geometry.coordinates)
    .setHTML(`<strong>${escapeHtml(p.name)}</strong> · ${p.ele} m`)
    .addTo(state.map);
}

function openPicker(feature) {
  const p = feature.properties;
  const id = String(p.id);
  const current = state.statuses.get(id)?.status ?? 'none';

  const el = document.createElement('div');
  el.className = 'peak-picker';
  el.innerHTML = `
    <h3>${escapeHtml(p.name)}</h3>
    <p class="peak-picker-meta">
      ${p.ele} m${p.prominence ? ` · ${p.prominence} m prominence` : ''}
      ${p.country && p.country !== '??' ? ` · ${p.country.split('/').map(c => COUNTRY_NAMES[c] ?? c).join(' / ')}` : ''}
    </p>
    <div class="peak-picker-options"></div>
    <div class="peak-picker-links">
      <a href="https://www.openstreetmap.org/node/${p.id}" target="_blank" rel="noopener">OSM</a>
      ${p.wikipedia ? `<a href="https://${wikipediaHost(p.wikipedia)}" target="_blank" rel="noopener">Wikipedia</a>` : ''}
      <a href="https://www.google.com/maps/dir/?api=1&destination=${feature.geometry.coordinates[1]},${feature.geometry.coordinates[0]}" target="_blank" rel="noopener">Directions</a>
    </div>
  `;

  const options = el.querySelector('.peak-picker-options');
  for (const key of [...TAGGED, 'none']) {
    const { label, color, hint } = STATUSES[key];
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = `peak-option${key === current ? ' is-current' : ''}`;
    btn.style.setProperty('--option-color', color);
    btn.title = hint;
    btn.textContent = label;
    btn.addEventListener('click', () => {
      setStatus(id, key);
      state.popup?.remove();
      flash(key === 'none' ? `${p.name} cleared` : `${p.name} → ${label}`);
    });
    options.appendChild(btn);
  }

  state.popup?.remove();
  state.popup = new maplibregl.Popup({ offset: 14, maxWidth: '320px', className: 'peak-popup' })
    .setLngLat(feature.geometry.coordinates)
    .setDOMContent(el)
    .addTo(state.map);
}

const wikipediaHost = tag => {
  const [lang, ...rest] = String(tag).split(':');
  return rest.length
    ? `${lang}.wikipedia.org/wiki/${encodeURIComponent(rest.join(':'))}`
    : `en.wikipedia.org/wiki/${encodeURIComponent(tag)}`;
};

// ─── Panel ────────────────────────────────────────────────────────────────────

function buildPanel(peaks) {
  const countries = [...new Set(
    state.features.flatMap(f => f.properties.country.split('/'))
  )].sort();

  const { minEle, maxEle } = state.filters;

  document.getElementById('peaks-panel').innerHTML = `
    <div id="peaks-counts" class="peaks-counts"></div>

    <section class="peaks-filters">
      <h3>Filters</h3>

      <label class="peaks-field">
        <span>Search</span>
        <input type="search" id="peaks-search" placeholder="Peak name…" autocomplete="off">
      </label>

      <label class="peaks-field">
        <span>Minimum elevation — <output id="peaks-min-out">${minEle} m</output></span>
        <input type="range" id="peaks-min" min="${minEle}" max="${maxEle}" step="50" value="${minEle}">
      </label>

      <label class="peaks-field">
        <span>Maximum elevation — <output id="peaks-max-out">${maxEle} m</output></span>
        <input type="range" id="peaks-max" min="${minEle}" max="${maxEle}" step="50" value="${maxEle}">
      </label>

      <fieldset class="peaks-field">
        <legend>Status</legend>
        <div class="peaks-checks" id="peaks-status-filters">
          ${[...TAGGED, 'none'].map(key => `
            <label class="peaks-check">
              <input type="checkbox" value="${key}" checked>
              <span class="peaks-swatch" style="background:${STATUSES[key].color}"></span>
              ${STATUSES[key].label}
            </label>
          `).join('')}
        </div>
      </fieldset>

      <fieldset class="peaks-field">
        <legend>Country</legend>
        <div class="peaks-checks" id="peaks-country-filters">
          ${countries.map(code => `
            <label class="peaks-check">
              <input type="checkbox" value="${code}">
              ${COUNTRY_NAMES[code] ?? code}
            </label>
          `).join('')}
        </div>
      </fieldset>
    </section>

    <section class="peaks-actions">
      <h3>Your list</h3>
      <div id="peaks-tagged" class="peaks-tagged"></div>
      <div class="peaks-buttons">
        <button type="button" id="peaks-export">Export JSON</button>
        <label class="peaks-import">
          Import
          <input type="file" id="peaks-import" accept="application/json,.json" hidden>
        </label>
      </div>
      <p class="peaks-note">
        Edits live in this browser. Export and commit the file as
        <code>data/peak-status.json</code> to share them across devices.
      </p>
      <p class="peaks-note peaks-source">
        ${state.features.length} peaks · snapshot ${peaks.generated ?? '—'} ·
        ${peaks.attribution ?? '© OpenStreetMap contributors'}
      </p>
    </section>
  `;

  wirePanel();
  renderTaggedList();
}

function wirePanel() {
  const search = document.getElementById('peaks-search');
  search.addEventListener('input', () => {
    state.filters.search = search.value;
    applyFilters();
  });

  const min = document.getElementById('peaks-min');
  const max = document.getElementById('peaks-max');
  const minOut = document.getElementById('peaks-min-out');
  const maxOut = document.getElementById('peaks-max-out');

  min.addEventListener('input', () => {
    if (Number(min.value) > Number(max.value)) max.value = min.value;
    state.filters.minEle = Number(min.value);
    state.filters.maxEle = Number(max.value);
    minOut.textContent = `${min.value} m`;
    maxOut.textContent = `${max.value} m`;
    applyFilters();
  });

  max.addEventListener('input', () => {
    if (Number(max.value) < Number(min.value)) min.value = max.value;
    state.filters.minEle = Number(min.value);
    state.filters.maxEle = Number(max.value);
    minOut.textContent = `${min.value} m`;
    maxOut.textContent = `${max.value} m`;
    applyFilters();
  });

  document.getElementById('peaks-status-filters').addEventListener('change', e => {
    const box = e.target;
    state.filters.statuses[box.checked ? 'add' : 'delete'](box.value);
    applyFilters();
  });

  document.getElementById('peaks-country-filters').addEventListener('change', e => {
    const box = e.target;
    state.filters.countries[box.checked ? 'add' : 'delete'](box.value);
    applyFilters();
  });

  document.getElementById('peaks-export').addEventListener('click', exportStatuses);
  document.getElementById('peaks-import').addEventListener('change', importStatuses);
}

function renderCounts() {
  const el = document.getElementById('peaks-counts');
  if (!el) return;

  const visible = visibleFeatures();
  const counts = Object.fromEntries(TAGGED.map(s => [s, 0]));
  for (const { entry } of taggedEntries()) counts[entry.status]++;

  el.innerHTML = `
    <div class="peaks-count peaks-count--total">
      <span class="peaks-count-value">${visible.length}</span>
      <span class="peaks-count-label">peaks shown</span>
    </div>
    ${TAGGED.map(key => `
      <div class="peaks-count">
        <span class="peaks-count-value" style="color:${STATUSES[key].color}">${counts[key]}</span>
        <span class="peaks-count-label">${STATUSES[key].label}</span>
      </div>
    `).join('')}
  `;
}

function renderTaggedList() {
  const el = document.getElementById('peaks-tagged');
  if (!el) return;

  const entries = taggedEntries();
  if (!entries.length) {
    el.innerHTML = '<p class="peaks-empty">Nothing tagged yet — click a peak on the map.</p>';
    renderCounts();
    return;
  }

  el.innerHTML = entries.map(({ id, entry, feature }) => `
    <button type="button" class="peaks-tagged-row" data-id="${id}" ${feature ? '' : 'disabled'}>
      <span class="peaks-swatch" style="background:${STATUSES[entry.status]?.color ?? '#888'}"></span>
      <span class="peaks-tagged-name">${escapeHtml(entry.name ?? feature?.properties.name ?? id)}</span>
      <span class="peaks-tagged-ele">${entry.ele ?? feature?.properties.ele ?? '?'} m</span>
    </button>
  `).join('');

  el.querySelectorAll('.peaks-tagged-row').forEach(row => {
    row.addEventListener('click', () => {
      const feature = state.features.find(f => String(f.properties.id) === row.dataset.id);
      if (!feature) return;
      state.map.flyTo({ center: feature.geometry.coordinates, zoom: 13.5 });
      openPicker(feature);
    });
  });

  renderCounts();
}

// ─── Export / import ──────────────────────────────────────────────────────────

function exportStatuses() {
  const peaks = {};
  for (const { id, entry } of taggedEntries()) peaks[id] = entry;

  const payload = {
    version: 1,
    updated: new Date().toISOString().slice(0, 10),
    peaks
  };

  const blob = new Blob([JSON.stringify(payload, null, 2) + '\n'], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = 'peak-status.json';
  link.click();
  URL.revokeObjectURL(url);

  flash(`Exported ${Object.keys(peaks).length} peaks`);
}

async function importStatuses(event) {
  const file = event.target.files?.[0];
  if (!file) return;

  try {
    const data = JSON.parse(await file.text());
    const incoming = data.peaks ?? data;
    if (typeof incoming !== 'object' || Array.isArray(incoming)) throw new Error('unexpected shape');

    let applied = 0;
    for (const [id, entry] of Object.entries(incoming)) {
      const status = entry?.status;
      if (!status || !(status in STATUSES)) continue;
      state.statuses.set(String(id), entry);
      const feature = state.features.find(f => String(f.properties.id) === String(id));
      if (feature) feature.properties.status = status;
      applied++;
    }

    saveLocalEdits();
    refreshSource();
    applyFilters();
    renderTaggedList();
    flash(`Imported ${applied} peaks`);
  } catch (err) {
    console.error('[peaks] import failed:', err);
    flash('That file is not a peak-status export', true);
  } finally {
    event.target.value = '';
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

let flashTimer = null;

function flash(message, isError = false) {
  let el = document.getElementById('peaks-flash');
  if (!el) {
    el = document.createElement('div');
    el.id = 'peaks-flash';
    document.body.appendChild(el);
  }
  el.textContent = message;
  el.className = `peaks-flash is-visible${isError ? ' is-error' : ''}`;
  clearTimeout(flashTimer);
  flashTimer = setTimeout(() => { el.className = 'peaks-flash'; }, 2600);
}

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, c =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])
  );
}
